### ISSUE TITLE
Values for options modified even if no changes

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1000]
Clean WP install - Go to Settings / Discussion - Click Save Changes.

You will see following strange result:

![changed_options](https://cloud.githubusercontent.com/assets/3008007/14829980/9be08256-0bee-11e6-9c9e-29dc78a8beee.jpg)

 `option_value = "0"` is replaced by `option_value =`

**Comment by octopuss** [comment]
@pavelevap this is default WordPress behaviour. When you try it on clean installation, option e.g. `comment_moderation` is set to `0`. After saving discussion settings in WP GUI option is set to empty value. In code saved data looks like this 
![screen shot 2016-04-27 at 8 37 51 am](https://cloud.githubusercontent.com/assets/2697437/14844045/ec3842d2-0c54-11e6-8161-f31eee9a580d.png)

**Comment by borekb** [comment]
Reopening. Even though this _might_ be technically fine, we should have at least an IniSerializerTest for this format and be 100% sure that this is correct. I agree with @pavelevap that it looks highly suspicious.

**Comment by borekb** [comment]
Sorry I focused too much on the INI format, this issue is primarily about changing the option value for apparently no good reason. Then @octopuss' answer is fine and we should really close this. I'll create a new issue for the suspicious INI format.

**Comment by pavelevap** [comment]
Oh, I did not notice that it is WordPress fault. I am not sure about the reason and maybe it should be reported to WP core. It was only suspicious to me :-)
