### ISSUE TITLE
Temporary option for splitting terms tracked

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1001]
After [upgrading](https://github.com/WordPress/WordPress/blob/e510918b4e85cdbe26690fe00117e60819f5689a/wp-admin/includes/upgrade.php#L1545) from WordPress 4.2.x, `term_split.lock` option is tracked and probably should be ignored. Or we could change minimum WordPress version for VersionPress to 4.3.x.

**Comment by borekb** [comment]
Thanks for spotting this. While it's technically a small bug, this should be pretty rare now and we'll focus on improvements for the future rather than the past.

Closing for now, if more people have this problem we'll reconsider.

**Comment by JanVoracek** [comment]
Since VP 4.0 it will be not relevant – #658

**Comment by pavelevap** [comment]
Right, I did not notice this ticket :-)

But generally, there should be any mechanism for checking entities? Every WP version could add some new options / postmeta (or remove them). This was only example of option which is relevant now, but will be obsolete in the future. I thought about searching WP codebase for parameters of general functions `add_option()` (it could be helpful also for plugins and themes in the future).

**Comment by borekb** [comment]
You mean some system to automatically detect removed or added options? That sounds like quite a lot of effort for relatively little benefit. I'd suggest watching this space and if this issue comes up again and again in the future, we could tackle it.
