### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by mikecastrodemaria** [versionpress/versionpress#1003]
After install RC :

Err messag : Plugin could not be activated because it triggered a fatal error

Parse error: syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in ...../wordpress/wp-content/plugins/versionpress/versionpress.php on line 51

**Comment by borekb** [comment]
Hi, this is a support issue, could you please open a new ticket [here](https://github.com/versionpress/support)? Thank you.
