### ISSUE TITLE
Staging urls (home, siteurl) should preserve origin protocol

### ISSUE THREAD

**Issue by octopuss** [versionpress/versionpress#1013]
If staging is created from a website which is running on HTTPS protocol, `home` and `siteurl` options are not preserving original protocol and use just HTTP. I think that `wp vp clone` should have optional parameter to change transfer protocol of staging environment. If ommited, protocol should be same.

**Comment by JanVoracek** [comment]
I think we don't need the parameter. User can specify whole URL, including the protocol.

**Comment by JanVoracek** [comment]
It will be probably fixed by PR #1019.

**Comment by JanVoracek** [comment]
I tested it on a workshop site. It works after #1019.
