### ISSUE TITLE
Full diff does not display empty added files

### ISSUE THREAD

**Issue by JanVoracek** [versionpress/versionpress#1014]
When I create new empty file and commit it, full diff displays following:
<img width="895" alt="screen shot 2016-04-28 at 14 23 35" src="https://cloud.githubusercontent.com/assets/703215/14885687/06072fc2-0d4d-11e6-8fed-df47b10e8523.png">

**Comment by octopuss** [comment]
I agree that it looks weird. So you mean that we should display at least empty diff table on the right side ?

**Comment by JanVoracek** [comment]
We should display it like GH does it:
<img width="693" alt="screen shot 2016-04-29 at 10 24 08" src="https://cloud.githubusercontent.com/assets/703215/14911306/e511c7de-0df4-11e6-9fe5-03968330428a.png">

We already use something similar for binary data:
<img width="606" alt="screen shot 2016-04-29 at 10 27 22" src="https://cloud.githubusercontent.com/assets/703215/14911319/fe748c48-0df4-11e6-8143-495c5882253a.png">
