### ISSUE TITLE
Local and remote environment error

### ISSUE THREAD

**Issue by andercard** [versionpress/versionpress#1033]
My question is how I can work in a real environment, I mean to have the site on bitbucket/github as a central repository and be able to work with my team taking a test site one live and the premises of our computers

I and tried to do so with git

* git push and git pull

then apply the changes with

* wp vp apply-changes

but the pages, posts and dublican comments

Thank you, this project is great just missing this solution and would be very good

![ff](https://cloud.githubusercontent.com/assets/10929498/14965855/33266006-1075-11e6-884f-2320b6c2868e.png)

Español
=============

mi pregunta es como puedo trabajar en un ambiente real, me refiero a tener el sitio en bitbucket/github como repositorio central y poder trabajar con mi equipo teniendo un sitio de prueba uno en vivo y los locales de nuestros computadores 

yo e probado hacerlo directo con git 

* git push y git pull 

después aplico los cambios con 

* wp vp apply-changes

pero las paginas, entradas y comentario de dublican

Gracias, este proyecto es grandioso solo faltaría esta solución y quedaría muy bien

**Comment by borekb** [comment]
Hi, this is a support issue, could you please open a new ticket [here](https://github.com/versionpress/support)? Thank you.
