### ISSUE TITLE
Plugin support, 4.0-alpha1 version

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1036]
Support for 3rd party plugins (and themes, to a lesser degree) is a major theme of v4.0. VersionPress needs to understand plugins' data and actions in order to provide version control for them.

Previous releases introduced things like [ChangeInfo objects](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/ChangeInfos/ChangeInfo.php), [schema format](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/Database/wordpress-schema.yml) ([readme](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/Database/schema-readme.md)) etc. which we're going to build upon and make more extensible. There will probably be many smaller, concrete tickets but in general, we should:

1. Support loading [DbSchemaInfo](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/Database/DbSchemaInfo.php) from **multiple schema-files**. For example, a WooCommerce site would load `wordpress-schema.yml` and `woocommerce-schema.yml`.
    - Similarly with [ShortcodesInfo](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/Database/ShortcodesInfo.php) and [`-shortcodes.yml`](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/Database/wordpress-shortcodes.yml) files.
2. Develop a **discovery mechanism for schema-files**. The idea is to look in three locations: VersionPress itself, plugin's source code (over time, schemata will hopefully ship with plugins if VersionPress becomes popular enough) or a central repository, possibly backed by a GitHub repo so that everyone can send a pull request.
3. **Reconsider ChangeInfo objects** structure and possibly simplify it (#1034). ChangeInfos (or equivalent) should also be shipped similarly to schema-files.
4. Work out a way to **describe actions**. We don't have a great abstraction for this yet, for example, actions are currently only described in PhpDoc sections of ChangeInfo files, cannot be processed automatically, etc. We already have technical tickets like #804 to improve this.

---

🚧 Current status: VersionPress' code is being refactored in **PR https://github.com/versionpress/versionpress/pull/1075**. Current status can be tracked in ➡️ https://github.com/versionpress/versionpress/pull/1075#issuecomment-239466089.

---

☝️  This ticket is a good place to solicit feedback from plugin authors. If you're one of them and would be interested in integrating with VersionPress, please let us know in the comments below. So far, we've heard interest from these plugins / folks:

- [Toolset / Types](https://wp-types.com/) – @zaantar
- [Pods Framework](http://pods.io/) – @sc0ttkclark
- [WooCommerce](https://www.woothemes.com/woocommerce/) – @pavelevap, @conschneider

---

Preliminary list of **things we'll likely need to improve in VersionPress** to support certain plugins:

- Dynamic table schemas – https://github.com/versionpress/versionpress/issues/1036#issuecomment-217214337
- Dynamic targets for standard references – https://github.com/versionpress/versionpress/issues/1036#issuecomment-217389148
- Ability to specify paths to ignore – https://github.com/versionpress/versionpress/issues/1036#issuecomment-219499106

**Comment by zaantar** [comment]
Just a detail about discovery mechanism for schema-files, IMHO it would be nice if plugins could also add/remove files by hooking into a filter provided by VersionPress.

**Comment by borekb** [comment]
@zaantar Good point, we currently don't provide any hooks or filters. Can you be more specific about the use case, how it would behave etc.? A concrete example would be appreciated. Thanks!

**Comment by pavelevap** [comment]
If plugin authors are not interested, I could try to support WooCommerce and bbPress. File `woocommerce-schema.yml` will be part of WooCommerce or VersionPress?

One example can be WPML and its `wpml-config.xml` files: https://wpml.org/documentation/support/language-configuration-files/

Note: Very important for plugins would be also modification of `wordpress-shortcodes.yml` file.

**Comment by borekb** [comment]
@pavelevap Good point about shortcodes, I've updated the original post.

If you'd like to try WooCommerce support, great! I'll put you in the list (tentative; if someone wants to join you, they can).

**Comment by zaantar** [comment]
@borekb I don't have anything complicated in mind... I assume that at some point VersionPress collects all the paths in an array, let's say `$schema_files`. Then it should be enough to add just one line:

```$schema_files = apply_filters( 'versionpress_filter_schema_files', $schema_files );```

So, plugin (or theme) authors could add multiple files or have them in arbitrary paths.

**Comment by zaantar** [comment]
Also, a similar approach could be used for adding a single schema. When you have all the files already parsed, there could be another filter for that array. That would allow for adding schemas or even removing conflicting ones by other parties... simply put, more flexibility.

In general, adding filters and actions wherever it seems only remotely sensible is IMHO a good practice in the WordPress world. :)

**Comment by borekb** [comment]
We don't add features speculatively so there'll need to be concrete use cases / demand for it but technically, I can imagine something like that working, yes.

**Comment by sc0ttkclark** [comment]
We have custom tables of data for Advanced Content Types, each with an ID field. We also have relationships which are stored in their own table `wp_podsrel`. Outside that, ensuring Pods integrates properly with Post Types, Taxonomies, Users, and Comments meta will be important to us.

**Comment by borekb** [comment]
@sc0ttkclark If you look at [wordpress-schema.yml](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/Database/wordpress-schema.yml) ([README](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/Database/schema-readme.md)), does it look like something that could work for Pods? The early feedback that we got from Types (Toolset) is that it works quite well with VersionPress already but I'm not sure whether Pods is technically similar or not.

**Comment by sc0ttkclark** [comment]
Yes that covers everything for us, however we'll need to hook into how you're versioning meta, if you're calling it directly from the database. If you're calling it through `get_post_meta( $post_id )` we won't have to do anything.

**Comment by sc0ttkclark** [comment]
Also still needs versioning purposed for our custom tables.

**Comment by borekb** [comment]
Sure, you would need to provide `pods-schema.yml` or something like that and then in the best case, everything would just magically work. (But things never go that smoothly with VersionPress, you can bet on that :) )

**Comment by sc0ttkclark** [comment]
Can you provide an example of a custom table schema?

**Comment by borekb** [comment]
If your plugin was creating a `wp_comments` table, storing comment entities, you'd provide a schema file containing [something like this](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/Database/wordpress-schema.yml#L36).

**Comment by sc0ttkclark** [comment]
It'd be great for plugin integrations if you could include an "example-schema.yml" file which shows an example of a plugin and it's table(s).

But would this be all I would add to a `pods-schema.yml`:

```
podsrel:
  table: podsrel
  id: id
  references:
    pod_id: post
    field_id: post
    related_pod_id: post
    related_field_id: post
```

See https://github.com/pods-framework/pods/blob/master/sql/dump.sql for our single table SQL schema.

This also doesn't address the unfortunate circumstance that your `.yml` files won't handle wildcards, will they?

```
pods_tbl:
  table: pods_*
  id: id
```

Our Advanced Content Types each get a table, but this is defined by the pod name the user provides.

For our `podsrel` schema we'd also like a custom reference, in which we can figure out whether `item_id` and `related_item_id` are related to a post, term, user, comment, or another Advanced Content Type table ID.

**Comment by borekb** [comment]
> It'd be great for plugin integrations if you could include an "example-schema.yml" file which shows an example of a plugin and it's table(s).

That's certainly coming – I guess a whole section of the documentation will be dedicated to this. You are "fortunate" enough to be one of the first guys to encounter these things :)

> But would this be all I would add to a pods-schema.yml

Yes that seems alright (at the basic level).

> For our podsrel schema we'd also like a custom reference, in which we can figure out whether item_id and related_item_id are related to a post, term, user, comment, or another Advanced Content Type table ID.

Options and postmeta do something like this so the schema format already supports what we call [value references](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/Database/schema-readme.md#value-references). Does it seem like it would be enough for Pods?

> Dynamic table schemas

We don't currently support this and it seems to me that it's the first really major thing we'll need to add to support Pods (and possibly other plugins that use this technique; are you aware of any others?). I'll be updating the original post with things like this, it will be turned into issues later.

Thanks for your great feedback!

**Comment by sc0ttkclark** [comment]
It looks like the value references would be what we want, except the key=>value part, if that line was left out would it work if we passed in `item_id` and `related_item_id`?

As far as custom tables per content type, I'm not sure how many plugins do everything that Pods does, there are lots that do the very tip of what we do but the functionality we bring is equivalent to what CCK does for Drupal, with nodes already in Drupal having their own tables.

**Comment by JanVoracek** [comment]
It will require some work but something like following example could work.

```yaml
podsrel:
  ...
  references:
    item_id: @some_function
    related_item_id: @other_function
```

**Comment by jevgen** [comment]
Badly need some doc on how to integrate with VersionPress, since Postman, WP-Activity and especially WPML are must haves on many websites.

**Comment by pavelevap** [comment]
We should also enable ignoring certain directories (and files), for example caching plugins (and many others) have its own folder in `wp-content`.

**Comment by sc0ttkclark** [comment]
Pods Alternative Cache stores cache files in wp-content/podscache/* when disk based caching is enabled.

**Comment by borekb** [comment]
@pavelevap Good point, adding it to the list of things we need to improve.

@sc0ttkclark thanks for confirming the usefulness of this.

**Comment by borekb** [comment]
Ok, after some internal discussion, here's an action plan for this issue:

- There will be **several PRs** that slowly but steadily implement the issue.
- The first one will be a **high-level** one, basically creating a Markdown document (`docs/Plugin-Support.md` or similar) that creates a specification / documentation similar to [`schema-readme.md`](https://github.com/versionpress/versionpress/blob/0df41a8ac3fade284cdd6deb213eb2ebad8d70b4/plugins/versionpress/src/Database/schema-readme.md). There are many unknowns yet so the document will be quite wild to begin with but it will give us common ground to coordinate the work around. Me, @JanVoracek and @pavelevap are expected to be the main contributors at the beginning.
- Then, there will be several **technical PRs** implementing various aspects of the plugin support. For example, Storages will need to be rewritten, ChangeInfo's reworked etc.
- **This issue** will keep collecting requirements from the community members / plugin authors and sum up some of the work done in related pull requests.

BTW, June is a good month to focus on this as there is WordCamp EU Vienna on 24th–26th. Most of the VersionPress team will be there so it's a good opportunity to discuss the technical details in person.

**Comment by borekb** [comment]
Renamed this issue to explicitly mention `4.0-alpha1` in which it ships.

**Comment by borekb** [comment]
:ship: Shipped in [4.0-alpha1](https://github.com/versionpress/versionpress/releases/tag/4.0-alpha1).

**Comment by adamrl84** [comment]
Howdy. My Team and I have been watching this project for a LONG time. I have finally started to play around with it and I'm at a point where I'd like to try helping wherever I can--provided I can convince the boss!


**Specific Inquiry:**
We have a plugin based on ACF that we use to build pages and layouts quickly. It makes extensive use of repeaters, flexible content fields and clone fields. ACF handles all field functions. We do compile CSS based off off options items selected, but that get ignored so isn't an issue.

Theoretically if we're not touching the database or creating our own post types, what is the bare minimum to start ensuring it is compatible via the YML files? I read some of the info but was looking at maybe a good plugin example to look at or more thorough guide.

Cursory testing shows most things to work, but I have had a couple of issues.

**Comment by leepeterson** [comment]
Curious to know the status of this from the standpoint of Pods integration. From what I've read here and in the related Pods ticket, everything should work very well.

Any unforeseen problems, corner cases or edge cases show up within the past half year? 

Again, specifically speaking to Pods/VersionPress setup.
