### ISSUE TITLE
Plugins, themes and WordPress installed via Composer

### ISSUE THREAD

**Issue by JanVoracek** [versionpress/versionpress#1037]
Compatibility with Composer is quite important for VersionPress. We use it to declare and install the dependencies since we decided to drop the compatibility with PHP 5.2. Now it's time to move forward and utilize Composer even more.

VersionPress should support plugins, themes or even WordPress installed via Composer. This includes :
 - installation, 
 - uninstallation, 
 - updates, 
 - undo / rollback etc.

Generally, VersionPress will work with `composer.json` and `composer.lock` and run according Composer commands. Also, `composer require`, `composer update` etc. could run some WP-CLI command to commit the changes.

I've created a Composer-based WordPress stack (codename [Pedestal](https://github.com/versionpress/pedestal)) inspired by Bedrock. We can utilize it to test the workflows with Composer.

**Comment by GaryJones** [comment]
I'll just mention the http://wecodemore.github.io/wpstarter/ stack as a nice compromise between the default arrangement and Bedrock. Having VersionPress support this established setup would be cool :-)

**Comment by borekb** [comment]
:ship: Shipped in [4.0-alpha1](https://github.com/versionpress/versionpress/releases/tag/4.0-alpha1).
