### ISSUE TITLE
caching plugin

### ISSUE THREAD

**Issue by morinoalaria** [versionpress/versionpress#1038]
My hosting company recommended that I use WP Super Cache to reduce server overhead (currently using Comet Cache). I was about to install it on one of my sites running VP, but I got a warning that the two plugins wouldn't work properly together.

If I can't use WP Super Cache, is there a caching plugin you would recommend? (I'm using VP 2.2, don't have a later version of php available on my server)

**Comment by octopuss** [comment]
This is a support issue, please open a new ticket in the [support repo](https://github.com/versionpress/support). Thanks.
