### ISSUE TITLE
Dockerized development environment

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1041]
Our [Dev-Setup](https://github.com/versionpress/versionpress/blob/master/docs/Dev-Setup.md) is quite complex and it would be better to provide pre-configured environment, built on Docker (which we love!). @JanVoracek already tried to prototype it and got quite far, however, Xdebug was not working properly. We should look at it again.

---

🏁 PR #1227

**Comment by JanVoracek** [comment]
I've created a [Dockerfile](https://github.com/versionpress/versionpress/files/268367/Dockerfile.txt) based on [this one](https://github.com/versionpress/demo-site/tree/40d61839c40b05220835f8f06e464b787d79d10f/versionpress_nginx_image). However, xdebug didn't work on the first try, second try, third try, ... Hence, I think someone with more experience should look at it.

**Comment by tatemz** [comment]
@JanVoracek In light of [versionpress/support#48](https://github.com/versionpress/support/issues/48), I think I can be of help.

At the moment, my [docker-versionpress image](https://hub.docker.com/r/tatemz/versionpress/), but I can definitely make arrangements to be more default.

Additionally, adding xdebug, node.js, and composer to the image should be fairly straight forward.

I'll see what I can do.

**Comment by tatemz** [comment]
@JanVoracek - Quick ❓ 

What version of node is advisable in your dev workflow for VP? In some of my dev on this Docker workflow, I am having some issues with `v6.2.1`.

**Comment by tatemz** [comment]
Also, I have [an initial Docker image](https://github.com/tatemz/docker-versionpress/tree/toolbox/toolbox) that I am working with. Feel free to run some tests:

## Shell into the toolbox
```
cd versionpress-repo
docker run --rm -it -v "$(pwd):/workspace" tatemz/versionpress:toolbox
```

## Run `npm`, `wp`, and `composer` commands
At the moment, no tests have been confirmed, but at least we have an image to play with.

**Comment by borekb** [comment]
I've started playing with this, let's see how far I can get. My todo list:

🏃 = work in progress

- [x] Build a basic Docker-based environment:
    - [x] WordPress latest on PHP 5.6
    - [x] WP-CLI and Git inside it
    - [x] MySQL
    - [x] Adminer
- [x] Map `<repo>/plugins/versionpress` into the container
- [ ] Git on the host should be able to inspect site repo
- [ ] DB tools on the host should be able to connect to the MySQL database
- [ ] Run tests in a container
    - [ ] Unit tests
    - [ ] Full integration tests (Selenium, maybe switch to Chrome headless)
    - [ ] Explore Travis CI integration
- [ ] Sort out `frontend` dev
- [ ] 🏃 Update Dev-Setup.md and Testing.md
