### ISSUE TITLE
vp restore-site error from freshly cloned repo

### ISSUE THREAD

**Issue by tatemz** [versionpress/versionpress#1046]
**The Error:**
```
Fatal error: Call to a member function resolve() on null in /var/www/html/content/plugins/versionpress/src/Cli/vp-internal.php on line 52
```
**Some Notes:**
- I am trying to restore a site using the 2nd scenario suggested method [here](http://docs.versionpress.net/en/feature-focus/wp-cli#vp-restore-site)
- I am using WP inside the subdirectory `wp`
- I am using a modified version of the official wordpress Docker container (with added mysql-client, wp-cli, and some install fixes to aid in the `wp` subdirectory)

UPDATE: Simply running `wp plugin activate versionpress` prior to the `wp vp restore-site` command worked.  I am assuming this was due to the plugin activation hook's setting up necessary configuration.

**Comment by borekb** [comment]
Thanks for the update, I will close this issue. In the future, please try posting into the [support repo](https://github.com/versionpress/support) first – it's a better place to report such things. Thanks.

**Comment by tatemz** [comment]
Okay, I can post this on that repo if you'd like, however, there is still a bug at play here, I think.

If the `vp restore-site` command is supposed to initialize the WordPress database, then it should be able to work without the plugin activated. 

My issue above was solved only because I ran these commands in this order:

1. `wp vp restore-site` (with necessary `--require` option) - **This command failed with the aforementioned error**
2. `wp plugin activate versionpress` (this only worked because the previous command did a half-installation)
3.  `wp vp restore-site` (with necessary `--require` option) - This command is identical to the first, but succeeded this time.

**Comment by borekb** [comment]
The `restore-site` command should certainly work as you suggest, i.e., without plugin activation (after all, the site is not properly set up yet). That's why this is a support issue – something strange is going on on your server. If you'd be so kind and copy the information to a [new support ticket](https://github.com/versionpress/support/issues/new), that would be great. Thanks!
