### ISSUE TITLE
Apply-changes doesn't pass allow-root

### ISSUE THREAD

**Issue by unclhos** [versionpress/versionpress#1049]
WP-CLI complains when running as root 

>  Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress install exists under.
> 
> If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.
> 
> If you'd like to continue as root, please run this again, adding this flag:  --allow-root
> 
> If you'd like to run it as the user that this site is under, you can run the following to become the respective user:
> 
> ```
> sudo -u USER -i -- wp <command>
> ```

Their "sudo" work around seems to be buggy too. 
"wp vp apply-changes" doesn't pass the "--allow-root" flag.

> root@host [2570 15:10:31 /******_/**_*****]# wp vp apply-changes --allow-root
> Error: Maintenance mode couldn't be switched. Details:
> 
> Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress install exists under.

**Comment by JanVoracek** [comment]
VersionPress's WP-CLI commands often call another internal subcommands; therefore this will be a more common issue. We need to fix all the occurrences.
