### ISSUE TITLE
Make End2End test workers non-static

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1064]
Workers have been a static property on End2End tests [since the beginning](https://github.com/versionpress/versionpress/issues/189#issuecomment-151111783). It's causing problems for me now (around 3.0.1 release) because `self::worker` is null in `PostTypeTestCase` (`PagesTest`, `PostsTest`). I hadn't seen this issue before and @octopuss could not reproduce it but it happens to me e.g. on commit https://github.com/versionpress/versionpress/commit/341bc677fceeaa86cab1fef4ed6e6d73e5b1eaa8 when I run `gulp run-tests`.

Just logging it for now, when I tried to move the worker initialization logic from [End2EndTestCase::staticInitialization()](https://github.com/versionpress/versionpress/blob/bd898332523ec68097315f3de7cf2e385537d208/plugins/versionpress/tests/End2End/Utils/End2EndTestCase.php#L49-L49) to the `setUp()` method of `PostTypeTestCase` and changed `worker` to be an instance variable, all worked fine.

**Comment by borekb** [comment]
Tried upgrading to PHPUnit 5.3.4 and still the same issue on commit https://github.com/versionpress/versionpress/commit/341bc677fceeaa86cab1fef4ed6e6d73e5b1eaa8.

**Comment by borekb** [comment]
Did a completely fresh checkout, went to commit https://github.com/versionpress/versionpress/commit/9a3808ec7f4df287dae8a7ff67a6dd0dfaa2dc3c which supposedly works for @octopuss and it failed with the same error.

Ok, I've done enough testing for now, will need someone else to try to reproduce it – could you please try, @pavelevap? It's really just a fresh checkout to that commit, then `npm install` & create `test-config.yml`, then `cd plugins/versionpress/tests` and run `gulp run-tests`. It should fail at around 88% with

```
Error: Call to a member function prepare_addPost() on null in
C:\...\versionpress\plugins\versionpress\tests\End2End\Utils\PostTypeTestCase.php:30
```

**Comment by pavelevap** [comment]
@borekb: Is this still relevant (there were so many changes)?

**Comment by borekb** [comment]
Probably not. Going to close this.
