### ISSUE TITLE
Improve invalid REST API response handling

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1074]
In #984, we've worked around the situation where the server (REST API) sends a malformed response, e.g., by including a PHP notice from some plugin. The `__VP__` key has been added to every JSON response so that the client-side JavaScript code can understand what is the real response. However, after some internal discussion, we're not sure this is the right approach.

This issue is about reconsidering our options here. Some initial comments:

- The current approach (as per #984) modifies the object and feels slightly weird. We'll probably abandon it.
- Every response could be wrapped in an object like this:

    ```
    {
      __VP__: true,
      data: theActualValue
    }
    ```

    The client would use something like `response.body.data.theActualValue` instead of `response.body.theActualValue`. This would also provide the opportunity to send additional metadata with every response should we need that, like what VersionPress or WP version are running on the server.
- The client could also reject to work if the response is malformed. I think we considered this #984 but in the end decided it is better for the users if the UI works despite some warnings in it. However, it could be argued that sending notices and such to the client is a security risk / server misconfiguration and we could just show some good error to guide the users to fix their server setup. This is a valid approach.

Let's do some research because the other projects relying on WP REST API must hit the same issue as well.

**Comment by borekb** [comment]
This Trac ticket is related: https://core.trac.wordpress.org/ticket/34915.

Since WP 4.5, all REST requests call `ini_set('display_errors', 0);` ([source](https://core.trac.wordpress.org/attachment/ticket/34915/34915.3.patch)). However, doesn't this create an issue on hosts that don't allow `ini_set()` in the first place? Those environments will paradoxically generate a PHP warning even for requests that might be otherwise fine, or no?

**Comment by pavelevap** [comment]
@borekb: I had the same problem with Ajax requests: https://core.trac.wordpress.org/ticket/26262#comment:24 and it should be [fixed](https://core.trac.wordpress.org/ticket/36708) in 4.5.3.

**Comment by borekb** [comment]
@pavelevap Thanks for the pointer.

But even with that, if `ini_set()` is disabled on a host (which I guess is not that rare; don't have any data on it though) and some WP plugin generates a notice, we still have the same problem, right?

**Comment by pavelevap** [comment]
Probably yes, mentioned fix is only for WP core.
