### ISSUE TITLE
[Question] Features

### ISSUE THREAD

**Issue by amiremami** [versionpress/versionpress#1078]
Hi
I'm following news for a while about your plugin, I haven't tried it. But some features from other plugins seems cool to me, I want to know do you provide these features in your plugin?

For example showing plugins modification date:
https://wordpress.org/plugins/plugin-modification-date/

Or some features from this plugin:
https://wordpress.org/plugins/stops-core-theme-and-plugin-updates/

For example disabling update notification for some plugins.

Thanks

**Comment by borekb** [comment]
Hi @amiremami,

> For example showing plugins modification date

We generally want to integrate better with existing wp-admin screens, see https://github.com/versionpress/versionpress/issues/1026. Not sure about this one in particular but yes, it would often be useful to see some versioning information on existing screens.

> Or some features from this plugin: https://wordpress.org/plugins/stops-core-theme-and-plugin-updates/ For example disabling update notification for some plugins.

This is likely out of scope of VersionPress.
