### ISSUE TITLE
Fix inconsistent and unclear naming convention of attributes

### ISSUE THREAD

**Issue by Ishirak** [versionpress/versionpress#1085]
This issue is part of a frontend code review, see #1083.

The front end codebase contains inconsistent and unclear attribute names.

For example, in the BulkActionPanel component there is a property **selected**. When you first encounter name of the property you think that the author probably meant a bool value. But a further examination of the component shows that it is actually an array of **Commit**s. Easy fix in this example would be to rename the property to **_selectedCommits_**.

Another problem are names of attributes containing a bool value. For example **loading**, **display** etc. Better names for these attributes could be **_isLoading_**, **_isVisible_** etc. But in this case I am open to discussion.

**Comment by vasek17** [comment]
Yes, I agree with both suggestions.

**Comment by borekb** [comment]
I agree too, let's do it.

**Comment by borekb** [comment]
:ship: Shipped in [4.0-alpha1](https://github.com/versionpress/versionpress/releases/tag/4.0-alpha1).
