### ISSUE TITLE
Fix inconsistent order of the React.js component’s (life cycle) methods

### ISSUE THREAD

**Issue by Ishirak** [versionpress/versionpress#1088]
This issue is part of a frontend code review, see #1083.

Several orders are used in the front end codebase. In some components the **render** method is the last one in the order, in the others is not. For clarity and readability of the codebase is preferred to use a consistent order. 

Most common order is with **render** method as the _last one_ in the component. An example of a consistent order can be found in the [Airbnb React/JSX Style Guide](https://github.com/airbnb/javascript/tree/master/react#ordering).

**Comment by vasek17** [comment]
OK, let's go with [Airbnb React/JSX Style Guide](https://github.com/airbnb/javascript/tree/master/react#ordering).

**Comment by borekb** [comment]
:ship: Shipped in [4.0-alpha1](https://github.com/versionpress/versionpress/releases/tag/4.0-alpha1).
