### ISSUE TITLE
Introduce a state management library

### ISSUE THREAD

**Issue by Ishirak** [versionpress/versionpress#1091]
_This issue is part of a frontend code review, see #1083._

Components, which communicate with APIs, must also change their state and render their logic and child components. Components also do more than just one thing, which do not help with clarity and readability of the components  (#1087). This technique is not at all suited for future front end codebase improvements and for implementation of new functionalities.

A state management library can, if designed properly, help with readability, clarity and possible future performance issues. Also any further changes and improvements will not be that much difficult, if done properly and when is #1087 resolved.

A few good state management libraries exist In the React.js ecosystem, so own implementation isn't necessary.

---
### [Flux](https://github.com/facebook/flux)
"Vanilla" library, the first one, who started all the Flux state management. The library requires a lot of boilerplate and knowledge of other libraries to achieve a performant app.

### [Redux](https://github.com/reactjs/redux)
Probably the most used one. The library took all the good things from the [Flux](https://github.com/facebook/flux), except for a need for a lot of boilerplate. Also heavily realies on the Immutability data collections, such as [Immutable.js](https://github.com/facebook/immutable-js/) library.

### [MobX](https://github.com/mobxjs/mobx)
Lately a lot of hype surrounds this library. Principe of this state management library is entirely different than Flux's or Redux's. Behind the scenes the library does a little bit of magic, so it is not as predictable as Redux or Flux, where developer has to do almost everything by himself, but thanks to the magic is the code really clean, app performs really well and the library doesn't require so much boilerplate. Even author of Redux, Dan Abramov, shared his [impression](https://twitter.com/dan_abramov/status/719866312240066560).

---
So these are possible options to choose from, if somebody has another tip for a state management library, feel free to share! My current pick, thanks to clarity, readability and not so much boilerplate, would be [MobX](https://github.com/mobxjs/mobx), but I'm always to open to suggestions.

**Comment by vasek17** [comment]
I'm familiar with Flux and Redux (which is like the industry standard today). I think Redux would be safe bet but it is very verbose.

I haven't used MobX - will have a look at it. Some first comments:
- I don't mind some magic when it is predictable and not so hard to debug.
- MobX looks it would play well with TypeScript (they even have "official" [React TypeScript boilerplate](https://github.com/mobxjs/mobx-react-typescript-boilerplate))
- It looks very clean and elegant

**Comment by borekb** [comment]
Have the same first impressions, MobX looks _really_ nice. My only concern is whether it is still predictable which is a strong point of Redux, as well as some really nice tooling around it (https://github.com/gaearon/redux-devtools). But from the code perspective, MobX seems more elegant.

**Comment by vasek17** [comment]
MobX have also interesting tools around (https://github.com/mobxjs/mobx-react-devtools).
The key part (performing actions) is not opinioned in MobX so it can done "the Redux way". 
It differs after an action is performed - Redux usually works with one single JS object as an application state which is passed via props to React components. After any change the root component is recursively re-rendered (but thanks to immutable objects only affected components need to re-render.

MobX has more Stores that have observable properties and it does a little magic in passing these stores to React components. I don't know how the re-rendering after change is done but D. Abramov [says](https://twitter.com/dan_abramov/status/719866312240066560) it's fast :)

**Comment by Ishirak** [comment]
As @vasek17 said, MobX has also interesting tool for debugging: [mobx-react-devtools](https://github.com/mobxjs/mobx-react-devtools). As for predictability, in the latest version MobX introduced [whyRun utility](https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#230), which helps in development – it can show why specific component needs to re-render itself and under which circumstances will re-render again.

As for actions, MobX introduced [@action](https://mobxjs.github.io/mobx/refguide/action.html) decorator in the [2.2.0 version](https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#220). Actions help with clarity a lot, especially in _strict_ mode. 

> In strict mode, MobX will throw an exception on any attempt to modify state outside an action.

[MobX 2.2: explicit actions, controlled mutations and improved DX]
(https://medium.com/@mweststrate/mobx-2-2-explicit-actions-controlled-mutations-and-improved-dx-45cdc73c7c8d#.psspyn2lz)

This means, that every state change has to be made in the actions. So in the one JavaScript class, in one place, there are [@observable](https://mobxjs.github.io/mobx/refguide/observable-decorator.html) values and [@action](https://mobxjs.github.io/mobx/refguide/action.html)s, which modify these values. On the other hand, Redux needs to specify reducers, actions and for clarity even constants. Another benefit of MobX actions is that an actions is wrapped in transaction – it doesn't matter how many changes of observable values an action handles, only after all of the changes are made, then MobX starts its "magic" process of evaluating all the necessary steps to re-render [@observer](https://mobxjs.github.io/mobx/refguide/observer-component.html) components.

But what really MobX does well is clean and elegant solution for a state management library. It also performs extremely well thanks to a little bit of "magic" behind the scenes, even without developer's optimalization. And even then is predictable, requires a little of boilerplate and its author really takes care of the project. For these reasons I'm **in** and I'd like to use it in our codebase.

**Comment by vasek17** [comment]
:heart: MobX

**Comment by borekb** [comment]
:ship: Shipped in [4.0-alpha1](https://github.com/versionpress/versionpress/releases/tag/4.0-alpha1).
