### ISSUE TITLE
Reconsider using TypeScript

### ISSUE THREAD

**Issue by vasek17** [versionpress/versionpress#1092]
This issue is part of a frontend code review, see #1083.

Originally written by @Ishirak.

Do we want to keep using TypeScript?
---------------------------------------------------

What advantage(s) does TypeScript have? Is current TypeScript codebase implementation clear enough? Can be current TypeScript codebase implementation improved? Does the team possess experience of another way of SPA development, especially with React.js library? Can be such an implementation clearer, more readable? And will it be the same in the future?

These are just examples of a few basic questions which the team has to ask and answer to. If the team uses TypeScript just for the intellisense or because it just looks like OOP language, then maybe is time to start looking around for more options. On the other hand, if the team uses TypeScript features which another development technique does not possess and can’t develop without these features, then change can be painful and not effective.

**Comment by vasek17** [comment]
My pros/cons on TypeScript.
Pros:
+ Static typing
+ Works on Windows (as opposed to [Flow](https://flowtype.org/))
+ Good support in IDEs (PHPStorm, Visual Studio Code)

Cons:
- No eslint support (however there are some [attempts](https://github.com/eslint/typescript-eslint-parser))
- Need to download definition files for 3rd party code - not a large problem after the start of project

**Comment by JanVoracek** [comment]
The question is what are the alternatives and is any of them significantly better?

**Comment by vasek17** [comment]
I think the main alternative is to omit types and use only Babel which is de facto standard these days.
It is faster and slightly better in some ways.
I don't know recent experience with Flow but it should do good work with static typing however they release new versions for Windows only once in a while.

**Comment by Ishirak** [comment]
As @vasek17 said, the React.js community is mainly divided into two categories: **TypeScript** and **Babel + ES6-7-next**. 

The Babel category is the larger one. Most of the JavaScript libraries are written using Babel and using new features isn't an issue. On the other hand TypeScript is really trying to add features which have a chance to make to the official ECMAScript standards. And as @vasek17 said, ironically is the TypeScript by Microsoft more platform free than the Flow by Facebook. But Flow looks really interesting and IDE support for non-types is slowly coming, see _Improved React support_ in the next version of [WebStorm](https://www.jetbrains.com/webstorm/nextversion/).

Personally I don't have much experience using TypeScript, but as a user of C#, it's not too hard to learn, so I don't think this will be an issue. But what I miss in TypeScript at the moment is object property spread, which will be in TypeScript 2.1, according to the [roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap#21).

**Comment by JanVoracek** [comment]
Slightly OT question: Since you are reconsidering TypeScript, does it mean we will rewrite most of the frontend within the review?

**Comment by borekb** [comment]
@JanVoracek Our TS code is pretty close to ES6/7 so that wouldn't be a big issue I think, however, from this discussion, it seems to me that there are not many strong reasons to leave TypeScript now. @Ishirak, I'd suggest you try using it for a while, at least you'll get some real-world experience with it and then we'll see. For v4, let's stick with it.
