### ISSUE TITLE
wp vp clone - masses of errors ?

### ISSUE THREAD

**Issue by mitchellkrogza** [versionpress/versionpress#1103]
Hi there

Trying to get Versionpress installed and working but ran sudo -u www-data -- wp vp clone --name=staging

and got thousands of lines of errors. Here's just the last few which ended with "Database Synchronized" and "All done - Clone created Here". Not leaving me feeling very sure it did anything correctly and certainly not happy to continue any further with this. No doubt it's user error and I probably missed having something crucial to this process installed.

Appreciate any help.

PHP Warning:  syntax error, unexpected '(' in Unknown on line 3
 in /var/www/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 165
Warning: syntax error, unexpected '(' in Unknown on line 3
 in /var/www/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 165
PHP Warning:  Invalid argument supplied for foreach() in /var/www/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 399
Warning: Invalid argument supplied for foreach() in /var/www/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 399
PHP Warning:  syntax error, unexpected '}' in Unknown on line 15
 in /var/www/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 165
Warning: syntax error, unexpected '}' in Unknown on line 15
 in /var/www/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 165
PHP Warning:  Invalid argument supplied for foreach() in /var/www/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 399
Warning: Invalid argument supplied for foreach() in /var/www/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 399
PHP Warning:  array_combine(): Both parameters should have an equal number of elements in /var/www/staging/wp-content/plugins/versionpress/src/Storages/DirectoryStorage.php on line 184
Warning: array_combine(): Both parameters should have an equal number of elements in /var/www/staging/wp-content/plugins/versionpress/src/Storages/DirectoryStorage.php on line 184
PHP Warning:  Invalid argument supplied for foreach() in /var/www/staging/wp-content/plugins/versionpress/src/Synchronizers/OptionsSynchronizer.php on line 70
Warning: Invalid argument supplied for foreach() in /var/www/staging/wp-content/plugins/versionpress/src/Synchronizers/OptionsSynchronizer.php on line 70
WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ON DUPLICATE KEY UPDATE option_value = VALUES(option_value), autoload = VALUES(a' at line 1 for query INSERT INTO k2bq173fg_staging_options (option_name, option_value, autoload) VALUES  ON DUPLICATE KEY UPDATE option_value = VALUES(option_value), autoload = VALUES(autoload); made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->_run_command, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, VersionPress\Cli\VPInternalCommand->finishInitClone, VersionPress\Synchronizers\SynchronizationProcess->synchronizeAll, VersionPress\Synchronizers\SynchronizationProcess->runSynchronizationTasks, VersionPress\Synchronizers\OptionsSynchronizer->synchronize, VersionPress\Database\Database->query
PHP Warning:  array_column() expects parameter 1 to be array, boolean given in /var/www/staging/wp-content/plugins/versionpress/src/Utils/ArrayUtils.php on line 130
Warning: array_column() expects parameter 1 to be array, boolean given in /var/www/staging/wp-content/plugins/versionpress/src/Utils/ArrayUtils.php on line 130
PHP Warning:  join(): Invalid arguments passed in /var/www/staging/wp-content/plugins/versionpress/src/Synchronizers/OptionsSynchronizer.php on line 101
Warning: join(): Invalid arguments passed in /var/www/staging/wp-content/plugins/versionpress/src/Synchronizers/OptionsSynchronizer.php on line 101
Success: Database synchronized
Success: All done. Clone created here:

**Comment by borekb** [comment]
Hi, this is a support issue, could you please open a new ticket [here](https://github.com/versionpress/support)? Thank you.
