### ISSUE TITLE
'wp vp clone' doesn't keep all database tables

### ISSUE THREAD

**Issue by coccoinomane** [versionpress/versionpress#1111]
When I clone a Wordpress installation with 'wp vp clone', it seems that only the default WP tables are cloned; 3rd-party plugin tables are excluded.

This makes sense from a VP perspective, but it always ends up breaking my cloned websites. I can fix the issue by copying the missing tables manually, but that's not great for UX.

Would it make sense to include an option for 'wp vp clone' whereby all tables are copied to the cloned website, even those that are not under version control? In this way, the cloned website would preserve its functionalities.

For example:

```
wp vp clone --name="staging" --dballtables
```

Thank you,
Guido

**Comment by borekb** [comment]
Hi, this is because 3rd party plugins are not supported yet. They are being worked on as part of #1036 which will be released in VersionPress 4.0.
