### ISSUE TITLE
Backend CSS selector too unspecific

### ISSUE THREAD

**Issue by tyrann0us** [versionpress/versionpress#1114]
WordPress 4.6, VersionPress 3.0.2

The following CSS selector in `versionpress/admin/public/icons/style.css` is too unspecific, overwriting `font-family` of non VersionPress elements which have the `icon-` class too:
`[class^="icon-"],
[class*=" icon-"] {
	font-family: 'icomoon'; 
	…
}`

I now this CSS is  from Icomoon but please consider prefixing it. Thanks!

**Comment by JanVoracek** [comment]
Thanks. You are right. It should be prefixed.
