### ISSUE TITLE
npm -> Yarn

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1142]
I've quickly tried [Yarn](https://yarnpkg.com/) and it was pretty impressive: our current dependencies were installed in about 10 seconds, compared to over 2 minutes with "good old npm". I see no reason not to switch (Yarn is [pretty compatible with npm](https://yarnpkg.com/en/docs/migrating-from-npm)).

**Comment by Ishirak** [comment]
I'm all in to use Yarn, but in #1140 @vasek17 introduced `types` instead of `typings` and according to [this issue](https://github.com/yarnpkg/yarn/issues/825) Yarn doesn't yet support this type of definition files. I'm sure that Yarn will suport it eventually, so I'd wait until it does so.

**Comment by vasek17** [comment]
What exactly do you mean by switch "npm -> yarn"? Adding a `yarn.lock` file to the repository? Changing [these](https://github.com/versionpress/versionpress/blob/203257484e5855e34cbb78a3e929019ff86e94f5/gulpfile.js#L273) [lines](https://github.com/versionpress/versionpress/blob/203257484e5855e34cbb78a3e929019ff86e94f5/gulpfile.js#L290) (Running `npm install` from gulp scripts)?

Yarn is compatible with npm (well, will be in future versions) so I would leave it on user to choose `npm install` or `yarn install` (and not enforce using `yarn`).

**Comment by borekb** [comment]
I'd switch to Yarn completely as I don't see any benefit of offering a choice (and maintaining two sets of lock files, documentation etc.).

There are some blockers, though, most prominently:

- https://github.com/yarnpkg/yarn/issues/825 as mentioned by @Ishirak 
- https://github.com/yarnpkg/yarn/issues/853 (preinstall / postinstall scripts)

**Comment by vasek17** [comment]
:+1:

**Comment by vasek17** [comment]
I still like more the optional way.  Anyone will be able to run `yarn install` instead of `npm install` but if he don't like/don't have `yarn` installed, it would still work wild "good old npm".

**Comment by borekb** [comment]
BTW, https://github.com/yarnpkg/yarn/issues/825 is fixed in Yarn 0.18, https://github.com/yarnpkg/yarn/issues/853 is now addressed as well.

**Comment by borekb** [comment]
With npm@5, I don't see any major benefits to using Yarn (actually, I personally think that npm is currently a bit better because of [Yarn's determinism](https://yarnpkg.com/blog/2017/05/31/determinism/) and the fact that Yarn 0.25 started putting Yarn version into the lock file which creates unnecessary merge conflicts). Feel free to comment or open a new issue if you think Yarn has some major benefits.
