### ISSUE TITLE
Sql functions in query strings stored as string on first commit

### ISSUE THREAD

**Issue by unclhos** [versionpress/versionpress#1146]
When using a sql function to create field values (UTC_TIMESTAMP) this is commited as a string in the ini file instead of the created value in the database. Subsequent changes (at least for my case) do update the ini file to the actual value but that might not happen before a push to another repo.

```
[970E56D1D48B4C7BBF3AAEEA7DEFB197]
title = "Form 2"
date_created = "UTC_TIMESTAMP()"
```

**Comment by JanVoracek** [comment]
@borekb I think it is more a bug than a new feature. VP should already handle these cases but it looks like it works only for updates.

**Comment by JanVoracek** [comment]
We should fetch the entity from DB in `WpdbMirrorBridge::processInsertQuery`.
