### ISSUE TITLE
Unnecessary files in release 4.0.alpha1.zip

### ISSUE THREAD

**Issue by ankurk91** [versionpress/versionpress#1154]
HI,

I just download latest alpha release.
https://github.com/versionpress/versionpress/releases/download/4.0-alpha1/versionpress-4.0-alpha1.zip

When i extracted the zip, i found several `.DS_Store` files in there.
Also there is a  file under `temp/_Nette.RobotLoader/_a8f7b475f99f14e7a8c92818c24898f8` which seems to contain some sensitive data. 

Are these files supposed to be in release zip ?

**Comment by borekb** [comment]
Thanks for the report, the ZIP should be clean of such stuff. Related: [this fulpfile task](https://github.com/versionpress/versionpress/blob/8f585b1635306fc95395f00e5b451c303ffe509a/gulpfile.js#L104).
