### ISSUE TITLE
Cloning to incorrect directory

### ISSUE THREAD

**Issue by tokelove** [versionpress/versionpress#1156]
I have a website at domain.com/public/htdocs

I use "wp vp clone --name=staging --siteurl=domain.com/staging"

It is a success, but it puts the cloned site in domain.com/public/staging which is obviously not going to be accessible. Is there a way to make it clone it into htdocs?

**Comment by borekb** [comment]
If `domain.com/public/htdocs` is a path then cloning to `domain.com/public/staging` is correct: the `clone` command always clones to a sibling directory. It's up to your web server configuration how this path is served.

The `--siteurl` parameter tells WordPress how the site will be accessible so you should create a web server configuration that maps `http://domain.com/staging` to your path `domain.com/public/staging`.

BTW your `--siteurl` parameter is missing either `http://` or `https://`.
