### ISSUE TITLE
PathUtils::getRelativePath() should be case-insensitive for the disk drive on Windows

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1158]
test-config.sample.yml [contains](https://github.com/versionpress/versionpress/blob/8f585b1635306fc95395f00e5b451c303ffe509a/plugins/versionpress/tests/test-config.sample.yml#L46) an example path like this:

```
# on Windows, the path is like c:/wamp/www/vp01
```

This doesn't work as the `PathUtils::getRelativePath()` is case insensitive and Windows use an upper-case C.

I'll update both the sample config file but also make the `getRelativePath()` method more permissive.

**Comment by JanVoracek** [comment]
I think it should be case-insensitive for whole paths on Windows – not only the drive letter.

**Comment by borekb** [comment]
I second that, however, that would be a bigger change to how the method works and also writings tests for it would be trickier. #1159 is a quick fix for the most problematic case (which I've already had in the past).
