### ISSUE TITLE
Schema changes for WordPress 4.7

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1164]
I will add overview of schema changes for new features in WordPress 4.7 and try to make a PR.

**Comment by borekb** [comment]
Excellent, thank you!

**Comment by pavelevap** [comment]
I found other complications with latest commit: https://github.com/versionpress/versionpress/commit/ccd3935ca4ebe80b2b3599d9bd035eabb83f96f0

1) 4 panels is only default value for Twenty Seventeen, child themes and plugins can easily change that with [twentyseventeen_front_page_sections](https://github.com/WordPress/WordPress/blob/dfbcdae985f6037895de2500cfb8e18fa4640212/wp-content/themes/twentyseventeen/inc/customizer.php#L95) filter. We would need something like that (not sure if possible with VP currently or I do not know the right syntax): `theme_mods_*["panel_{integer}"]: post`

2) Because of asterix in `theme_mods_*` it will work automatically for child themes (which is good), but there is a possible conflict. It will "work" for all themes, even if they use the same option name for example for a string or HTML content (which is not good). So, maybe we should extract this rule and add it to special `schema.yml` for Twenty Seventeen (and child themes)?

**Comment by borekb** [comment]
1. Regex `\d` could be used here.
2. Do you have an example of how this would look? Thanks.

**Comment by pavelevap** [comment]
ad 2) Examples:

- Default Twenty Seventeen: We can use hardcoded option `theme_mods_twentyseventeen`, but child themes will be not supported.
- Child theme: We can use asterix `theme_mods_*` for handling different options, for example `theme_mods_twentyseventeen-child`, etc. It is common to use parent theme name in child theme, for example `twentyseventeen-child`, but it is not required and it can be also `my-custom-2017`. But we can use also `theme_mods_twentyseventeen*` to support only some child themes and avoid conflicts (see next point).
- But there are possible conflicts when using for example premium theme (`theme_mods_premium-theme`) with custom options with the same name `panel_1` and `panel_2` (common names). And when they do not contain entities, but only text with numbers, for example address "Street 12", it will be converted to entities in this case (number 12 to VPID).

So, ultimate solution is using `theme_mods_*`, but only for Twenty Seventeen (and child themes). But in this case this rule should be added to special `schema.yml` file only for this theme (and applied when theme is active).

**Comment by borekb** [comment]
I see, so `theme_mods_*` is perfectly fine in something like `wp-content/themes/twentyseventeen/.versionpress/schema.yml` (or whatever ends up being the path for theme schemas) but might cause conflicts in the core `schema.yml` file, correct?

Would something like `theme_mods_twenty*` be a reasonable workaround until theme schemas are supported properly?

**Comment by pavelevap** [comment]
Yes, exactly!

Yes, this workaround should work for most of child themes and it is probably the best solution for now. I will add related commit and we should finally take care of this problem in #1176.
