### ISSUE TITLE
Function getMenuReference() is broken

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1168]
Following `value-reference` in [schema.yml](https://github.com/versionpress/versionpress/blob/325cd8335b4083a17d2e489c5b72b018f7f103eb/plugins/versionpress/.versionpress/schema.yml#L30) does not work:

`_menu_item_object_id: '@\VersionPress\Database\VpidRepository::getMenuReference'`

I probably found the cause, after some tests I will add details and hopefully PR.

**Comment by pavelevap** [comment]
Function was broken since VP 3.0: https://github.com/versionpress/versionpress/pull/913/commits/b4b165395c8705611706432bb78b9342b2f72d22

`$menuItemType` was changed and `$database->get_col` no longer returns `string` but `array`, so conditions were broken. I added quick fix, but maybe there should be some tests, I am not sure...

**Comment by borekb** [comment]
👍 

Yes, tests should be added, could you open a PR please?
