### ISSUE TITLE
W3TC Incompatiablity - Spam Commits

### ISSUE THREAD

**Issue by SippieCup** [versionpress/versionpress#1174]
When Versionpress is running, a commit is made every few seconds in vpdb/options/w3_extensions_hook.ini

Its a 1 line change which updates a timestamp for an auto-update check.

I would usually just put the file in the .gitignore file, but I cant seem to figure out where the modification is actually occurring.

Anyone know how to work around this?

**Comment by pavelevap** [comment]
Hi,

plugin definition for W3TC does not exist yet, but you can try to create one. You will have to add `w3_extensions_hook` option as `ignored-entities` or `frequently-written`.

Plugin support is [available](https://blog.versionpress.net/2016/10/versionpress-4-0-alpha/) in latest 4.0-alpha1 version ([download](https://github.com/versionpress/versionpress/releases)). You can find detailed manual [here](https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md) or use [example](https://gist.github.com/JanVoracek/b5530707ff19e3ccf1b85978d271e0bd) for WooCommerce (not complete).

I'm closing this issue for now, but feel free to open new [support question](https://github.com/versionpress/support/) if you need further help.

P.S. I am not familiar with W3TC code, but maybe it could be also bug on its side and timestamp is updated too frequently.
