### ISSUE TITLE
Only positive numbers considered as entity

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1182]
Related to #1161 and #1164.

After [this](https://github.com/versionpress/versionpress/commit/5812c8ddffbf51cb65e6210d35185f27843ff4c4) commit, `custom_css_post_id` is considered as entity (related to `post`). But default value is `-1` (when there is no CSS change for particular theme) and this negative value should not be considered as entity?

![image](https://cloud.githubusercontent.com/assets/3008007/21566594/a412f548-cea4-11e6-98ba-80547d4fccf7.png)

I am not sure, but there should be probably some kind of possibility to define interval for `value-references` in `schema.yml` (or hook)? Solution with `-1` can be common for plugin authors, I guess.

**Comment by JanVoracek** [comment]
We need to adjust [this function](https://github.com/versionpress/versionpress/blob/0e3dea27d3d070fc8ca7d3ba9d6271170f2263c6/plugins/versionpress/src/Database/VpidRepository.php#L207-L210).
