### ISSUE TITLE
Uninstall utility assumes ChangeInfo type

### ISSUE THREAD

**Issue by mravery** [versionpress/versionpress#1183]
See https://github.com/versionpress/support/issues/73#event-908916686 for more context.

When VP is installed on a WP deployment that is already using git for versioning, it will not be able to uninstall correctly. This is because (from the filed issue above):

> getScope is a function defined in the TrackedChangeInfo class but it isn't a part of the ChangeInfo interface. When an UntrackedChangeInfo object gets stored, it doesn't have a getScope() method, but the code assumes that the object is one of the other types of ChangeInfo objects.

The fix is to replace [line 40](https://github.com/versionpress/versionpress/blob/325cd8335b4083a17d2e489c5b72b018f7f103eb/plugins/versionpress/src/Utils/UninstallationUtil.php#L40) of `UninstallationUtil.php` with this:

`return method_exists($changeInfoList[0], "getScope") && $changeInfoList[0]->getScope() === 'versionpress' && $firstChangeInfo->getAction() === 'activate';`

**Comment by borekb** [comment]
@mravery Would you mind creating a PR with the proposed solution? It looks good!
