### ISSUE TITLE
Adding VP_WP_CLI_BINARY option to vp config

### ISSUE THREAD

**Issue by LorincJuraj** [versionpress/versionpress#1186]
I am running  VersionPress on my shared cPanel hosting. The problem is that I was not able to create global `wp` alias for WP-CLI. I had to modify VersionPress files to include full path to WP-CLI binary. This changes will be lost with next update. 

The solution would be to create a new `vp config` option for the WP-CLI path (simmilar to `VP_GIT_BINARY`) so you can change the WP-CLI path just by running something like
 `wp vp config VP_WP_CLI_BINARY '/custom/path/to/wp-cli.phar'`

**Comment by LorincJuraj** [comment]
I am currently working on this here 364271463e5fb61eb5c5d385a157609a620d6afa .

Everything seams to be working just fine so far, but it will be great if someone can test the more advanced features (Debugging, Frontend...) as I do not have much experience with the tools used there.

I don't want to do the PULL REQUEST just yet until it's fully tested.

**Comment by borekb** [comment]
Very cool, feel free to open a PR early, no worries if the code needs further changes (it looks good at first sight).
