### ISSUE TITLE
Random GUID not generated for attachments

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1188]
VP is using [vp_generate_post_guid()](https://github.com/versionpress/versionpress/blob/81239e533d1e94fb609cfcb0503384880497e7f4/plugins/versionpress/setup-hooks.php#L699) to generate random GUID which is not based on URL.

But following code works only for standard post types:

`add_filter('wp_insert_post_data', 'vp_generate_post_guid', '99', 2);`

Uploaded attachments are using different hook `wp_insert_attachment_data`, see [here](https://github.com/WordPress/WordPress/blob/f3a9d2bd9a9be240785855564225ffe933d49482/wp-includes/post.php#L3271).

**Comment by borekb** [comment]
@pavelevap https://github.com/versionpress/versionpress/commit/2ab13439b8a67e5334e6aa69eba086fef4ff889a looks good, could you please create a PR for it? Thanks.
