### ISSUE TITLE
Clean up temp folder

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1192]
We should automatically remove everything from `temp` folder during build, except versioned [files](https://github.com/versionpress/versionpress/tree/master/plugins/versionpress/temp).

@vasek17 mentioned similar [condition](https://github.com/versionpress/versionpress/blob/325cd8335b4083a17d2e489c5b72b018f7f103eb/gulpfile.js#L116) on Slack as an example.

**Comment by pavelevap** [comment]
Probably also remove `.DS_Store` from main folder.

**Comment by borekb** [comment]
Duplicate of https://github.com/versionpress/versionpress/issues/1192.
