### ISSUE TITLE
Required versions of WordPress, PHP and Git for 4.0-beta

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1200]
Before releasing 4.0-beta, we should consider after some time again what versions to require. I think it should be:

- **WordPress ~~4.7~~ 4.8** (why not)
- **PHP 5.6+** (no change here).
- **Git 2.x**. We'll likely still technically support 1.9 but there have been many 2.x releases in the meantime and having up to date Git is strongly recommended.

---

- [x] Update RequirementsChecker
- [x] Docs

**Comment by strarsis** [comment]
Would this release be stable enough to be used on production without warning?

**Comment by borekb** [comment]
Hi @strarsis, v4 will be much closer to it but still marked as "developer preview". I plan to publish a blog post soon explaining the roadmap in more detail; you guys deserve it.
