### ISSUE TITLE
"Error: Maintenance mode couldn't be switched."

### ISSUE THREAD

**Issue by wokadeh** [versionpress/versionpress#1202]
VersionPress version 3.0.2
WordPress version 4.7.4
php 7.0.15-0 ubuntu0.16.04.4
git version 2.7.4

I got his failure pulling to my Staging system from my Live system:

```

# wp vp pull --from=live --allow-root
Error: Maintenance mode couldn't be switched. Details:

Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress install exists under.

If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.

If you'd like to continue as root, please run this again, adding this flag:  --allow-root

If you'd like to run it as the user that this site is under, you can run the following to become the    respective user:

sudo -u USER -i -- wp <command>

```

Why do I get this error? 
What can I do to prevent it?
Why do I get the error doing this command as root when I already use the flag --allow-root?

Best regards

**Comment by borekb** [comment]
Hi, this is a support issue, could you please open a new ticket [here](https://github.com/versionpress/support)? Thank you.

**Comment by JanVoracek** [comment]
Actually, it is a bug in our WP-CLI commands. It is already reported here: https://github.com/versionpress/versionpress/issues/1049. Generally, `wp vp` commands does not work with the `--allow-root` parameter because internally they call another WP-CLI commands and do not pass the parameter.
