### ISSUE TITLE
Compatibility for WordPress 4.8

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1217]
WordPress 4.8 will come with some new features, we will have to update definitions:

- [x] Define entities for `attachment_id` in `widget_media_audio`, `widget_media_image` and `widget_media_video` options.

**Comment by Mac1an** [comment]
Thank you.

**Comment by Mac1an** [comment]
Looking forward to it.

**Comment by pavelevap** [comment]
I went through [developers docs](https://make.wordpress.org/core/tag/dev-notes+4-8/) and I did not notice anything else relevant to VersionPress.
