### ISSUE TITLE
parse error when i try to clone my site

### ISSUE THREAD

**Issue by chazragg** [versionpress/versionpress#1235]
so i would like to implement versionpress onto my current website but i seem to be running in an issue 

the command i am using is wp vp clone --name=test --require=wp-content/plugins/versionpress/src/Cli/vp.php

(reason i use --require is because 1and1 runs php 5.5 and it is required :P)

when i run the command it says there is a parse error: syntax error, unexpected '.', expecting '&' or variable (t_variable) in GitRepositor.php on line 491

i don't know much about the git files and didn't want to go root round an changing stuff.

if you require any more information feel free to ask and i will provide.

**Comment by borekb** [comment]
Hi, this is a support issue, could you please open a new ticket [here](https://github.com/versionpress/support)? Thank you.
