### ISSUE TITLE
[Question] (Media) files?

### ISSUE THREAD

**Issue by strarsis** [versionpress/versionpress#1242]
Does VersionPress also versionize media files? Does it intelligently skip the files generated automatically (e.g. for multiple resolutions)? If not, what tool would work great together with VersionPress? The uploads/ folder content should be in sync with the VersionPress state for a specific backup point (in time) - otherwise media files or other files used by plugins may be missing after restoring a VersionPress change state.

**Comment by pavelevap** [comment]
Hi @strarsis,

sorry, not yet, improvements for media files are planned for version 5.0, please see #492.
Currently all media files are tracked and stored in Git repository, which is not very efficient, but it works for all situations. If you have any custom solution for media uploads, you can add your `uploads` path to `.gitignore`.

We have another repo for support issues and you are welcome there with other questions: https://github.com/versionpress/support
