### ISSUE TITLE
Can not commit changes to Git

### ISSUE THREAD

**Issue by vukhanhtruong** [versionpress/versionpress#1273]
Here are steps I was followed:

- Resolved the conflict
- Commited changes to Git  **=> I got stuck here**
- Ran wp vp apply-changes to have them reflected on the staging site

That is the message I got  "fatal: could not open '.git/COMMIT_EDITMSG': Permission denied"
So, I can not push my changes to Live site.

Thanks for your support.

**Comment by borekb** [comment]
You have to have permissions to write to the site files (they can be owned e.g. by `www-data` or something). Can you check that the permissions are right?

If you need to follow this conversation, please open a new ticket in the [`support` repo](https://github.com/versionpress/support)? Thank you.

**Comment by vukhanhtruong** [comment]
Permissions are right. I solved it by deleting .git/COMMIT_EDITMSG. Weird!
Thank you very much for your support. Keep your good work up.
