### ISSUE TITLE
Use `vp_entity_should_be_saved_{$entity}` filter on initialization

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1274]
Example: Create some subcategory on clean WP site to allow `category_children` to be created in database. Then activate VersionPress and `category_children.ini` file is created. Go to Posts - Categories and create some category, you will see that `category_children` was deleted.

![image](https://user-images.githubusercontent.com/3008007/27948295-a68692fa-62f9-11e7-91a8-8a6e7cfa996c.png)

All `{$taxonomy}_children` options should be ignored, but they are not directly added in `schema.yml` file, [vp_entity_should_be_saved_option ](https://github.com/versionpress/versionpress/blob/ccb7442229da1c9697ecdd06551a7bb9d8ea5c93/plugins/versionpress/.versionpress/hooks.php#L53) filter is used. And that is probably why `category_children.ini` file is created during VersionPress initialization (and later removed by [vp_flush_regenerable_options()](https://github.com/versionpress/versionpress/blob/0ecf1d2a49d0e7cf63df88e23807c42d0fec104d/plugins/versionpress/internal-functions.php#L15)).

**Comment by JanVoracek** [comment]
`vp_entity_should_be_saved_{$entity}` filters should be used on initialization. I will update the title of this issue.
