### ISSUE TITLE
Cannot install the plugin

### ISSUE THREAD

**Issue by ericft** [versionpress/versionpress#1287]
VersionPress could not be activated:
https://screencast.com/t/cQ0CwGukeO2

It seems to have an issue with the compilation.

Thank you

**Comment by pavelevap** [comment]
Hi @ericft,

how did you install VersionPress? Did you download latest installation `.zip` package from [here](https://github.com/versionpress/versionpress/releases)?

**Comment by borekb** [comment]
Hi @ericft, this is a support issue, we have a [support repo](https://github.com/versionpress/support) for that (this repo is used to organize work on code). If you need further help, could you please open a new issue there? Thank you!
