### ISSUE TITLE
Publish plugin in WordPress official repos

### ISSUE THREAD

**Issue by francescobianco** [versionpress/versionpress#1291]
There no is plugin inside official WP repos
https://wordpress.org/plugins/
Did I can put it??

**Comment by borekb** [comment]
We will publish VersionPress in the official repository once it leaves the Developer Preview mode. This will take a couple more releases.

**Comment by borekb** [comment]
An update on this:

We still want to publish to the w.org repo after the [Developer Preview](https://docs.versionpress.net/en/getting-started/about-eap) ends (around v5 or v6), however, we've been recently considering publishing it as "VersionPress Preview", slug `versionpress-preview`. The point of this would be to clearly indicate the project status and separate support forums and ratings from the eventual stable release. However, this would not be allowed by the w.org repo administrators: "We will absolutely not give you a different slug. No chance", see the [Slack conversation](https://wordpress.slack.com/archives/C1LBM36LC/p1515880931000060) with Otto.

So we can only publish as VersionPress / `versionpress` and for that, we'll wait as noted above. Until then, VersionPress will be available from GitHub.
