### ISSUE TITLE
couldn't add a page to a menu w.o. deactivating VersionPress (alpha1)

### ISSUE THREAD

**Issue by jpeyret** [versionpress/versionpress#1292]
I can't edit menus under **Appearance/Menus, Pages, Add to Menu.**  When I do that the browser cursor goes into spinning mode and doesn't stop, i.e. the change is under way but never completes.

I restarting the browser.  No effect.  Then restarting the vm (`shutdown -r now`) to make sure the wordpress or another process wasn't stuck somehow.  No effect.

What did work was temporarily deactivating VersionPress.  Then I can add the page, save the menu.  Restart versionpress, all ok.

No big deal, but since I didn't find this under your issues, thought you'd wanna know.  Txs for good job.

**env:  Version 4.0-alpha1, WordPress 4.8.2, Theme:  The Ark, on a Bitnami WordPress vm.**

**Comment by pavelevap** [comment]
Hi @jpeyret,

sorry for troubles, but I tried clean installation and everything works well.

1) Could you please use latest VersionPress version `4.0-beta` ([download](https://github.com/versionpress/versionpress/releases))?

2) Could you try to use default WordPress theme (for example Twenty Seventeen)? The Ark is premium theme which can cause problems or conflicts.

Do you have any details about your error? Could you attach screenshot related to your browser console with errors? Could you look at your PHP logs to check possible errors?

Thank you!

**Comment by pavelevap** [comment]
Hi @jpeyret,

if you need further help, could you please open a new issue in our [support repo](https://github.com/versionpress/support)? Thank you!

**Comment by jpeyret** [comment]
no problem w closing. since I had the workaround (deactivating VisionPress), this was more of a heads up anyway.  

if I do encounter it again, I'll reopen and try to provide you with some of the diagnostics info you were suggesting.

**Comment by BreezeMaxWeb-NS** [comment]
Also had the same issue, connection is dropped and admin-ajax.php never returns a response with VersionPress activated.
