### ISSUE TITLE
I could not install

### ISSUE THREAD

**Issue by httpiago** [versionpress/versionpress#1293]
I tried installing in many ways but always Wordpress returned a "no valid plugin found" error.
It should be easier to install

**Comment by pavelevap** [comment]
Hi @httpiago,

what did you try to install? Did you downloaded latest [version](https://github.com/versionpress/versionpress/releases/download/4.0-beta/versionpress-4.0-beta.zip) from [Releases](https://github.com/versionpress/versionpress/releases) page?

**Comment by pavelevap** [comment]
Hi @httpiago,

if you need further help, could you please open a new issue in our [support repo](https://github.com/versionpress/support)? Thank you!
