### ISSUE TITLE
"wp vp activate" doesn't check if VersionPress is already active

### ISSUE THREAD

**Issue by x1024** [versionpress/versionpress#1313]
https://github.com/versionpress/versionpress/blob/73ff46674828218c271bbcaf820c50ff4cdf8cd4/plugins/versionpress/src/Cli/vp.php#L164

Steps to reproduce:
* I installed and activated the plugin, then followed the activation procedure in the admin panel of my website. The site was successfully activated, and a .git repo with an initial commit was created in the project's root.
* Then I took a look at the CLI, and the first command was "wp vp activate". I decided to run it, for no particular reason.
* I was surprised to see that the command attempted to "activate" the site a second time.

Suggestion:

Add a check for "VersionPress::isActive()" at the start of the activate() function, and if VP is already active - print a log message and quit.

**Comment by borekb** [comment]
Thanks, that indeed sounds like a small thing to improve. Would you be willing to send a PR? Thanks!
