### ISSUE TITLE
'wp' is not recognized, but wp-cli works fine and versionpress is activated

### ISSUE THREAD

**Issue by josuevalrob** [versionpress/versionpress#1328]
What I did:

- Git clone from the repository into new-site
- Install in new-site the versionpress pluing
- Activate the versionpress plugin
- run the wp vp restoresite command
- ` wp vp restore-site --siteurl="http://localhost:8080/new-site"`

It give me the next error: 

> Error: Failed creating database. Details:
> "wp" no se reconoce como un comando interno o externo,
> programa o archivo por lotes ejecutable.

which means: _Error: Failed creating database. Details:"wp" is not recognized as an internal or external command, program or batch file executable_.

After running that, versionpress get desactivated, so if I run again the restore-site command I get this: 

>  Error: Unfortunately, this site was not tracked by VersionPress.
>             Therefore, it cannot be restored.

**Comment by pavelevap** [comment]
Hi @josuevalrob,

do you use latest VP version `4.0-beta`? WP-CLI is installed and working? Did you tried to define `VP_WP_CLI_BINARY` (see [details](https://github.com/versionpress/versionpress/issues/1186))?

**Comment by josuevalrob** [comment]
VP: Version 4.0-beta
WP-CLI 1.5.0
Commands like` wp db create` works fine.

**Comment by josuevalrob** [comment]
I found the problem... I had a problem in my environment variables. But yeah, the problem was related to the location of the wp-cli, the versionpress can not find it. 

Thanks

**Comment by borekb** [comment]
@josuevalrob Glad that you got it sorted! We have a [dedicated support repo](https://github.com/versionpress/support) so if you encounter issues like this in the future, feel free to post there.
