### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by mugurcagdas** [versionpress/versionpress#1331]
Dear Sir/Madam,

I am computer engineer and graphic designer. I use your plugin in my customers' websites. I appreciate that.
I am writing you because I want to design a logo for this plugin.
May I ask, do you need a logo for this plugin?

Kindly waiting your answer.

Best Regards,
Musa Ugur Cagdas
Computer Engineer/Graphic Designer

**Comment by borekb** [comment]
In a true open source spirit, feel free to send a pull request :)

**Comment by mugurcagdas** [comment]
Hello Sir,

I made the design for this plugin.
Did you like my design? We can change any part which you don't like.
I have vector files too. I can send you if you want to.
Could you please let me know that will you use this design? If so I will send you PR.
Kindly waiting your answer :)

![card](https://user-images.githubusercontent.com/35704934/40183971-c236fc10-59f7-11e8-8c68-80fd13fe3e94.png)
![sonsonasset 3](https://user-images.githubusercontent.com/35704934/40184002-da7dc4ac-59f7-11e8-862c-734a49b257e4.png)
![mockup black t-shirt](https://user-images.githubusercontent.com/35704934/40184067-fda0a3a0-59f7-11e8-91e4-8e2ecea5d4f9.jpg)

--
Best Regards,
Musa Ugur Cagdas
Computer Engineer/Graphic Designer

**Comment by toshotosho** [comment]
Could you produce a set of banners for the plugin directory? See the requirements [here](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#filenames)

**Comment by mugurcagdas** [comment]
Hello @toshotosho OFC! I will update you soon.

**Comment by toshotosho** [comment]
@mugurcagdas I admire your enthusiasm, but keep in mind, [https://versionpress.net/](https://versionpress.net/), which is the official site of the plugin, already has a logo.

**Comment by mugurcagdas** [comment]
Thanks for your interest.
Actually I saw that before and i create my design similar to first logo for compatibility between old brand identity and new brand identity. For example: Colors similar with first logo, green wave coming from first logo too.
I just waiting their answers because I feel honored if they use my logotype.
Kindly waiting answers.

**Comment by borekb** [comment]
@mugurcagdas VersionPress branding is a bit more complicated than that because we also have a hosted service, [VersionPress.com](https://versionpress.com/), which needs to be taken into account as well. I'm not super-proud of what we have today but it's also quite unlikely that we would be changing both logos and related graphics _unless_ it feels jaw-dropping and 100% right. But your effort is certainly appreciated!
