### ISSUE TITLE
Git Version

### ISSUE THREAD

**Issue by DoganM95** [versionpress/versionpress#1355]
Please Extend your Readme.md to link a tutorial on how to update an outdated git version server sided,
as this plugin needs git 1.9+ but the most recent wordpress installer ships with git 1.8.

**Comment by borekb** [comment]
Hi @DoganM95, thanks for the suggestion, however, WordPress doesn't ship with any version of Git and how to get it installed or updated for your particular server is up to that specific system. For example, it works differently between Windows vs. Ubuntu vs. other distros, so we can't reasonably provide good guidance for all of them. I also think it's relatively well-documented for each major system so don't feel this would be time well-spent. Hope this makes sense.

I'm going to close this issue but feel free to comment further or open an issue in the `versionpress/support` repo.

**Comment by DoganM95** [comment]
Alright, thank your for your Time :)
