### ISSUE TITLE
Is this project dead or near death?

### ISSUE THREAD

**Issue by michacassola** [versionpress/versionpress#1364]
Hi,

I've noticed there is not much development going on here. Will there ever be a stable version?
Or is this project basically abandoned?

**Comment by borekb** [comment]
Hi @michacassola, VersionPress is used by many individuals and companies for their production workflows _if they are developers_ so I wouldn't call it "dead" but you're right that there hasn't been much activity lately. We as the original team don't currently have capacity to work on it but we've not abandoned the project either – there is every intention to return to it when we can, and it should replace the staging technology on VersionPress.com one day.

**Comment by michacassola** [comment]
Hi @borekb ,
thank you for that detailed answer! I shall have my eye on this project then. :)

It would be a nice usecase to separate a production site from a staging site and merge them back together once the development on the staging site is done.

**Comment by borekb** [comment]
That's a big point of what we're doing 😄 

I'm going to close this issue now, if you have any further questions, feel free to open a new one.

**Comment by michacassola** [comment]
So can I use VersionPress as designer? I am not afraid of code but am not practiced in anything besides CSS. If it is ready to use but lacks some ease of use I am also willing to write a tutorial.

**Comment by borekb** [comment]
As long as things go smoothly, you're good to use use it. But when they don't, you'll probably need to understand / debug a little bit of PHP code.
