### ISSUE TITLE
restore-site doesn't work with Wordpress 5.1

### ISSUE THREAD

**Issue by candrews** [versionpress/versionpress#1374]
When running `wp vp restore-site --yes --siteurl="${SITE_URL}" --require=wp-content/plugins/versionpress/src/Cli/vp.php` with `wp-config.php` present against an empty database (with no database tables), it fails with this output:
```
Success: Database tables created
PHP Fatal error:  Cannot redeclare wptexturize() (previously declared in /var/www/html/wp-includes/formatting.php:51) in /var/www/html/wp-includes/formatting.php on line 315
Error: Could not finish site restore
```

It works fine with Wordpress 5.0.

**Comment by borekb** [comment]
Hmm, any ideas what that could be? Found a Trac ticket https://core.trac.wordpress.org/ticket/43609 related to 5.1 but that one seems to be fixed / closed for quite some time already.

**Comment by candrews** [comment]
> Hmm, any ideas what that could be? Found a Trac ticket https://core.trac.wordpress.org/ticket/43609 related to 5.1 but that one seems to be fixed / closed for quite some time already.

I'm not sure exactly what changed from Wordpress 5.0 to 5.1 causing this issue, but the PR I created does fix the problem. And it seems like a good improvement as it's a nice, defensive change.

**Comment by borekb** [comment]
That indeed does look good, thanks!
