### ISSUE TITLE
Testing is problematic on Linux

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1383]
As [mentioned](https://gitter.im/versionpress/versionpress?at=5c7d56b1d2d62067b741fbd2) by @candrews on Gitter, running tests is currently problematic on Linux (Craig uses Fedora if that's important). The core VersionPress team only uses macOS or Windows so we're not really sure what's going on on Linux but it already lead to PRs such as #1371, #1379 or #1380 which sometimes feel a bit arbitrary to me. Are we doing something fundamentally wrong about permissions, filesystem or something like that?

We'd appreciate help from those of you with Linux / Docker experience. Our dockerized dev stack was built primarily in these two pull requests:

- https://github.com/versionpress/versionpress/pull/1227 (merged July 2017)
- https://github.com/versionpress/versionpress/pull/1329 (merged June 2018)

@candrews, could you possibly involve someone from Isobar?

**Comment by borekb** [comment]
@candrews could you please try this?

```
docker run --rm -it -v $PWD/dev-env/testfolder:/var/www/html versionpress/wordpress:cli /bin/sh
```

Does this run successfully and create `dev-env/testfolder` on your host system? From within the container, is `/var/www/html` owned by www-data? Thanks.

**Comment by borekb** [comment]
This is an issue from the official WordPress image repository talking about Fedora and FS permissions, seems possibly related to me: https://github.com/docker-library/wordpress/issues/132.

**Comment by candrews** [comment]
Due to SELinux, the command should use `z` or `Z`, so I actually ran:
`docker run --rm -it -v $PWD/dev-env/testfolder:/var/www/html:z versionpress/wordpress:cli /bin/sh`

> Does this run successfully and create `dev-env/testfolder` on your host system?

Yes.
From the host:
```
$ ls dev-env/testfolder/ -la
total 8
drwxr-xr-x. 2 root root 4096 Mar  5 16:20 .
drwxr-xr-x. 3 root root 4096 Mar  5 16:20 ..
```

> From within the container, is `/var/www/html` owned by www-data? Thanks.

No. from within the container:
```
$ ls -la /var/www/
total 20
drwxr-xr-x    1 root     root          4096 Mar  2 02:57 .
drwxr-xr-x    1 root     root          4096 Mar  2 02:57 ..
drwxr-xr-x    2 www-data www-data      4096 Mar  2 02:57 .wp-cli
drwxr-xr-x    2 root     root          4096 Mar  5 21:20 html
```

**Comment by borekb** [comment]
`/var/www/html` should be owned by www-data as seen by the container, is there a way to achieve that on Fedora? For other Linux distributions, [this tricks](https://github.com/versionpress/versionpress/blob/b14fe014360ae36597ac2fd18effa801de566f31/dev-env/wordpress-cli-image/Dockerfile#L21-L24) seems to work.

It's really an underlying issue with Docker as many people complain in https://github.com/moby/moby/issues/2259.

**Comment by borekb** [comment]
Tests are passing in a Linux VM on Travis (#1415), @candrews, could you please confirm that you can run tests fine on your Fedora machine?

**Comment by borekb** [comment]
I'm going to close this for now, @candrews, if you still hit any issues on Fedora, feel free to reopen.
