### ISSUE TITLE
Merge driver doesn't work on Debian-based systems

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1384]
We currently maintain two implementations of a Git merge driver, [`ini-merge.sh`](https://github.com/versionpress/versionpress/blob/b14fe014360ae36597ac2fd18effa801de566f31/plugins/versionpress/src/Git/merge-drivers/ini-merge.sh) and [`ini-merge.php`](https://github.com/versionpress/versionpress/blob/b14fe014360ae36597ac2fd18effa801de566f31/plugins/versionpress/src/Git/merge-drivers/ini-merge.php). The `.sh` one is used on Linux and macOS systems and we tried to make it compatible with various Bash and `sh` implementations, see e.g. https://github.com/versionpress/versionpress/commit/a6e05c032c5919c81fb4102cf00535c7e773e53e. However, it seems that we found one that doesn't work, through a failed [`CloneMergeTest#dateModifiedMergesAutomatically`](https://github.com/versionpress/versionpress/blob/e2209836d30889727991365fde2c983d0121e5a1/plugins/versionpress/tests/Workflow/CloneMergeTest.php#L88) test.

(Note: for a while, we thought that the problem is in the test, see PR #1376 and an issue #1382 but it's really a Bash / sh incompatibility.)

This test runs on our [WordPress Docker image](https://github.com/versionpress/versionpress/blob/b14fe014360ae36597ac2fd18effa801de566f31/dev-env/wordpress-image/Dockerfile) which is based on [wordpress:php7.2-apache](https://github.com/docker-library/wordpress/blob/b8bfd453a65ce574982d328103aaa2850997cede/php7.2/apache/Dockerfile) which is based on **debian:stretch-slim**. For comparison, the merge driver is also tested by `MergeDriverTest`, specifically by [`mergedDatesWithoutConflict`](https://github.com/versionpress/versionpress/blob/b14fe014360ae36597ac2fd18effa801de566f31/plugins/versionpress/tests/GitRepositoryTests/MergeDriverTest.php#L133) and all is fine there. The only substantial difference is that these tests run on the [`versionpress/wordpress:cli` image](https://github.com/versionpress/versionpress/blob/b14fe014360ae36597ac2fd18effa801de566f31/dev-env/wordpress-cli-image/Dockerfile) which is based on [wordpress:cli](https://github.com/docker-library/wordpress/blob/b8bfd453a65ce574982d328103aaa2850997cede/php7.2/cli/Dockerfile) which is based on **Alpine Linux**.

I'm not quite sure if the "stretch-slim" image is heavily customized or if the bug affects all Debian-based distributions but it's quite bad anyway as it would affect all users of the official WordPress Docker image.

The best way to fix this would be to re-implement the merge drive in Go as suggested in #736 and drop both the Shell and PHP implementations. It's a relatively ugly and fragile code and we don't want to maintain it twice.

I'll keep this issue open until the Go implementation is ready.

**Comment by candrews** [comment]
Have you run `shellcheck` to see what bashisms exist?

A go implementation sounds good, but I'm concerned about how long that will take.

**Comment by borekb** [comment]
If I remember correctly, @JanVoracek ran shellcheck when improving the scripts compatibility with `sh` (https://github.com/versionpress/versionpress/commit/a6e05c032c5919c81fb4102cf00535c7e773e53e). We're actually surprised that Debian has the problem and Alpine doesn't – it's usually the other way around :)

Go implementation is the only sustainable solution I'm afraid. The code is not long so hopefully we'll be able to get it done soon, or get help from some Go programmer. In the meantime, if you know how to fix the shell script, we'd be happy to accept a PR.

**Comment by borekb** [comment]
(Yes, ShellCheck passes on [the current `ini-merge.sh`](https://github.com/versionpress/versionpress/blob/b14fe014360ae36597ac2fd18effa801de566f31/plugins/versionpress/src/Git/merge-drivers/ini-merge.sh).)
