### ISSUE TITLE
Copying some files from container to host is not permitted

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1405]
When I run Workflow tests and then want to copy files with `npm run tests:copy-files-to-host`, there are errors for all `wptest/.git/objects`:
`cp: can't create '/tmp/wp-copy/./wptest/.git/objects/7e/d4240c8b8b19034b726a300c401b0696f271fb': Operation not permitted`
Folder `wptest/.git/objects/7e` is created on my computer, but files inside are not copied.

Folder with cloned site `wptestclone` is copied without problems.

**Comment by borekb** [comment]
Thanks for reporting this, I'll take a look. For reference, the copy functionality has been introduced in https://github.com/versionpress/versionpress/commit/8dbf2a0e2049fb9a1845159bd2a5b15fa2f426e7 / PR https://github.com/versionpress/versionpress/pull/1396.

**Comment by borekb** [comment]
I have tried this yesterday and all worked fine. @pavelevap, could you please try if you can still reproduce on the latest `master` version?

**Comment by pavelevap** [comment]
It is still happening for me, I am not sure what is going on here :-( I played a little bit with `copy-files-to-host`:

Original command:
https://github.com/versionpress/versionpress/blob/4977ced4e496c7b0194fca75d8e503526b42c998/docker-compose-tests.yml#L75
Error: `cp: can't create '/tmp/wp-copy/./wptestclone/.git/objects/61/c94bb9b3194099fa777b3e2e80ce6b9e43043e': Operation not permitted` (for all files from `wptestclone/.git/objects`).

But I was able to copy these files successfully with different commands, for example: `'/bin/sh -c "cp -a /tmp/wp/wptestclone/.git/objects/. /tmp/wp-copy/objects-test/"'`

And also following command worked: `'/bin/sh -c "cp -a /tmp/test-logs/. /tmp/test-logs-copy/; cp -a /tmp/wp/wptest/. /tmp/wp-copy/wptest/; cp -a /tmp/wp/wptestclone/. /tmp/wp-copy/wptestclone/"'` In this case everything was copied like with original command. So, different command, same files, but without errors, strange.

Then I tried original command once againg and error was back :ghost: 
File permissions seems OK, with different command it is possible to copy these files.

And one more note, in my original description was error related to `wptest`, but now it is `wptestclone`.

**Comment by pavelevap** [comment]
I was not able to reproduce this issue with another PC (Windows 10 Pro, Hyper-V, Docker Desktop).
Probably somehow related to my slow machine, Windows 7 or Docker Toolbox. 👻
But we can close it for now, I guess, until somebody reproduces it (or finds any explanation).
