### ISSUE TITLE
tell vp which existing git repo to use

### ISSUE THREAD

**Issue by trebitzki** [versionpress/versionpress#1406]
My local dev site folder has a site repo and a symlinked wordpress repo from https://github.com/WordPress/WordPress.git. VP has latched onto the wrong one, the wordpress repo should not be touched, as this would interfere with remote fetching.

Is there a way to make vp switch to my dev repo?

**Comment by borekb** [comment]
Hi, could you please describe the directory layout you're trying to achieve? Site's `.git` is a clone of `WordPress/WordPress`, right? Where would you expect VersionPress' `.git` folder to be?

Not sure if this helps you but there are configuration options `VP_PROJECT_ROOT` and `VP_GIT_BINARY` (that could perhaps be configured to point to another repo using Git's `--git-dir` flag; I haven't tried that). See [Configuration](https://docs.versionpress.net/en/getting-started/configuration/).

**Comment by borekb** [comment]
@trebitzki, I'm going to close this issue as part of housekeeping but feel free to open a new one in https://github.com/versionpress/support if you have more info to share. Thank you.
