### ISSUE TITLE
Double serialized value not serialized/deserialized correctly

### ISSUE THREAD

**Issue by candrews** [versionpress/versionpress#1430]
I haven't yet been able to come up with shorter/simpler reproduction steps or a unit test. If someone does, please let me know - I'll keep working on it as well.

The problem can be reproduced by:
* Start with a VersionPress enabled Wordpress instance
* Install this plugin: https://wordpress.org/plugins/miniorange-saml-20-single-sign-on/
* In the wp-admin configuration for the plugin, set the x509 certificate to:
```
-----BEGIN CERTIFICATE-----
 MIIDnDCCAoSgAwIBAgIGAV2hzwAUMA0GCSqGSIb3DQEBCwUAMIGOMQswCQYDVQQG
 EwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNj
 bzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMM
 Bmlzb2JhcjEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTAeFw0xNzA4MDIw
 NzE3MDRaFw0yNzA4MDIwNzE4MDNaMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
 Q2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0
 YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMMBmlzb2JhcjEcMBoGCSqG
 SIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
 AQoCggEBAJqzbApk1LTFnGF9E3OvS9fZkcRbHoiLVHyqnE5+ZIUsL3qBwgXbLlg1
 aiV3y5QCpv/SoDYNTkmG8Af5PC+qEFDqA1UnqDs3epJtK/SLLdRHNTJjesLXtgWL
 8YxcVh0FQkDUBUmOomEfokGU1oda+jjxYcee/zF7IUcETenWRmM5RXPvMxOVeSsq
 6ecc1z84gYiuD2qUR/WpZsA3A83K1O+kGhM56qkjlb9X1yco9vavw0NI+m70pSri
 VhcETrIZZpT1I4G3DRPAnStnoLFyp44WGPd8S4G3dSjClA4+cdTphKZL5nKin02F
 NGNB3sv+ubmsmsHUnTzkyr18iXKRbxMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
 CQW2NW9GjtkcZRImC+l9hSlDZ5NYvgjGE67arPdrbS1EDjmpOdz7E7yLEU6mpzsO
 xMsi5kta9rQhsOdbydz6swkkUxrhSm7lBbttkggHULN1dfhLMUmbBDCZ9cmfRZCo
 D0dW+bHjH4aDd3X1uguoGjoxTMaR3EM5z663rA3ogjRTbsdag4sjlpoVah40y0vi
 tVl4j/Uxn/VzzG1yGmPffrv8AWG4Zll9ZjIowbE9MnHdcMgj6sPBYJ7J1iVwlRMj
 9F8SeUPTzQhnh/40TH3KNVU6QSb5J1W4gCrRwxQ0HDlCZOAZyL5JJoIlGTqCbF5b
 AcPvBc/ggs5jNB6jaqLJ/A==
 -----END CERTIFICATE-----
```
* `wp option get saml_x509_certificate` The output correctly returns:
```
a:1:{i:0;s:1334:"-----BEGIN CERTIFICATE-----
MIIDnDCCAoSgAwIBAgIGAV2hzwAUMA0GCSqGSIb3DQEBCwUAMIGOMQswCQYDVQQG
EwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNj
bzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMM
Bmlzb2JhcjEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTAeFw0xNzA4MDIw
NzE3MDRaFw0yNzA4MDIwNzE4MDNaMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
Q2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0
YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMMBmlzb2JhcjEcMBoGCSqG
SIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAJqzbApk1LTFnGF9E3OvS9fZkcRbHoiLVHyqnE5+ZIUsL3qBwgXbLlg1
aiV3y5QCpv/SoDYNTkmG8Af5PC+qEFDqA1UnqDs3epJtK/SLLdRHNTJjesLXtgWL
8YxcVh0FQkDUBUmOomEfokGU1oda+jjxYcee/zF7IUcETenWRmM5RXPvMxOVeSsq
6ecc1z84gYiuD2qUR/WpZsA3A83K1O+kGhM56qkjlb9X1yco9vavw0NI+m70pSri
VhcETrIZZpT1I4G3DRPAnStnoLFyp44WGPd8S4G3dSjClA4+cdTphKZL5nKin02F
NGNB3sv+ubmsmsHUnTzkyr18iXKRbxMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
CQW2NW9GjtkcZRImC+l9hSlDZ5NYvgjGE67arPdrbS1EDjmpOdz7E7yLEU6mpzsO
xMsi5kta9rQhsOdbydz6swkkUxrhSm7lBbttkggHULN1dfhLMUmbBDCZ9cmfRZCo
D0dW+bHjH4aDd3X1uguoGjoxTMaR3EM5z663rA3ogjRTbsdag4sjlpoVah40y0vi
tVl4j/Uxn/VzzG1yGmPffrv8AWG4Zll9ZjIowbE9MnHdcMgj6sPBYJ7J1iVwlRMj
9F8SeUPTzQhnh/40TH3KNVU6QSb5J1W4gCrRwxQ0HDlCZOAZyL5JJoIlGTqCbF5b
AcPvBc/ggs5jNB6jaqLJ/A==
-----END CERTIFICATE-----";}
```
* Run `wp vp apply-changes`
*  `wp option get saml_x509_certificate` The output is now incorrect:
```
<<<serialized>>> <<<serialized>>> <array>
```

Both before and after running `wp vp apply-changes`, `wp-content/vpdb/options/sa/saml_x509_certificate.ini` has not changed; the file contents are:
```
[saml_x509_certificate]
option_value = <<<serialized>>> <<<serialized>>> <array>
option_value[0] = "-----BEGIN CERTIFICATE-----
MIIDnDCCAoSgAwIBAgIGAV2hzwAUMA0GCSqGSIb3DQEBCwUAMIGOMQswCQYDVQQG
EwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNj
bzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMM
Bmlzb2JhcjEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTAeFw0xNzA4MDIw
NzE3MDRaFw0yNzA4MDIwNzE4MDNaMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
Q2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0
YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMMBmlzb2JhcjEcMBoGCSqG
SIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAJqzbApk1LTFnGF9E3OvS9fZkcRbHoiLVHyqnE5+ZIUsL3qBwgXbLlg1
aiV3y5QCpv/SoDYNTkmG8Af5PC+qEFDqA1UnqDs3epJtK/SLLdRHNTJjesLXtgWL
8YxcVh0FQkDUBUmOomEfokGU1oda+jjxYcee/zF7IUcETenWRmM5RXPvMxOVeSsq
6ecc1z84gYiuD2qUR/WpZsA3A83K1O+kGhM56qkjlb9X1yco9vavw0NI+m70pSri
VhcETrIZZpT1I4G3DRPAnStnoLFyp44WGPd8S4G3dSjClA4+cdTphKZL5nKin02F
NGNB3sv+ubmsmsHUnTzkyr18iXKRbxMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
CQW2NW9GjtkcZRImC+l9hSlDZ5NYvgjGE67arPdrbS1EDjmpOdz7E7yLEU6mpzsO
xMsi5kta9rQhsOdbydz6swkkUxrhSm7lBbttkggHULN1dfhLMUmbBDCZ9cmfRZCo
D0dW+bHjH4aDd3X1uguoGjoxTMaR3EM5z663rA3ogjRTbsdag4sjlpoVah40y0vi
tVl4j/Uxn/VzzG1yGmPffrv8AWG4Zll9ZjIowbE9MnHdcMgj6sPBYJ7J1iVwlRMj
9F8SeUPTzQhnh/40TH3KNVU6QSb5J1W4gCrRwxQ0HDlCZOAZyL5JJoIlGTqCbF5b
AcPvBc/ggs5jNB6jaqLJ/A==
-----END CERTIFICATE-----"
autoload = "yes"
```

**Comment by pavelevap** [comment]
I can confirm this issue, but this problem is related to double serialization in plugin [SAML SP Single Sign On – SSO](https://wordpress.org/plugins/miniorange-saml-20-single-sign-on), see https://plugins.trac.wordpress.org/browser/miniorange-saml-20-single-sign-on/tags/4.8.70/login.php#L351:

`update_option( 'saml_x509_certificate', maybe_serialize( $saml_x509_certificate ) );`

`$saml_x509_certificate` is serialized manually by [maybe_serialize()](https://developer.wordpress.org/reference/functions/maybe_serialize/) and then once again during update_option() automatically.

It is saved as **double serialized** value in database:
```
s:1354:"a:1:{i:0;s:1334:"-----BEGIN CERTIFICATE-----
MIIDnDCCAoSgAwIBAgIGAV2hzwAUMA0GCSqGSIb3DQEBCwUAMIGOMQswCQYDVQQG
EwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNj
bzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMM
Bmlzb2JhcjEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTAeFw0xNzA4MDIw
NzE3MDRaFw0yNzA4MDIwNzE4MDNaMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
Q2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0
YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMMBmlzb2JhcjEcMBoGCSqG
SIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAJqzbApk1LTFnGF9E3OvS9fZkcRbHoiLVHyqnE5+ZIUsL3qBwgXbLlg1
aiV3y5QCpv/SoDYNTkmG8Af5PC+qEFDqA1UnqDs3epJtK/SLLdRHNTJjesLXtgWL
8YxcVh0FQkDUBUmOomEfokGU1oda+jjxYcee/zF7IUcETenWRmM5RXPvMxOVeSsq
6ecc1z84gYiuD2qUR/WpZsA3A83K1O+kGhM56qkjlb9X1yco9vavw0NI+m70pSri
VhcETrIZZpT1I4G3DRPAnStnoLFyp44WGPd8S4G3dSjClA4+cdTphKZL5nKin02F
NGNB3sv+ubmsmsHUnTzkyr18iXKRbxMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
CQW2NW9GjtkcZRImC+l9hSlDZ5NYvgjGE67arPdrbS1EDjmpOdz7E7yLEU6mpzsO
xMsi5kta9rQhsOdbydz6swkkUxrhSm7lBbttkggHULN1dfhLMUmbBDCZ9cmfRZCo
D0dW+bHjH4aDd3X1uguoGjoxTMaR3EM5z663rA3ogjRTbsdag4sjlpoVah40y0vi
tVl4j/Uxn/VzzG1yGmPffrv8AWG4Zll9ZjIowbE9MnHdcMgj6sPBYJ7J1iVwlRMj
9F8SeUPTzQhnh/40TH3KNVU6QSb5J1W4gCrRwxQ0HDlCZOAZyL5JJoIlGTqCbF5b
AcPvBc/ggs5jNB6jaqLJ/A==
-----END CERTIFICATE-----";}";
```

`wp option get saml_x509_certificate` returns (only once) unserialized value:

```
a:1:{i:0;s:1334:"-----BEGIN CERTIFICATE-----
MIIDnDCCAoSgAwIBAgIGAV2hzwAUMA0GCSqGSIb3DQEBCwUAMIGOMQswCQYDVQQG
EwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNj
bzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMM
Bmlzb2JhcjEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTAeFw0xNzA4MDIw
NzE3MDRaFw0yNzA4MDIwNzE4MDNaMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
Q2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0
YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMMBmlzb2JhcjEcMBoGCSqG
SIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAJqzbApk1LTFnGF9E3OvS9fZkcRbHoiLVHyqnE5+ZIUsL3qBwgXbLlg1
aiV3y5QCpv/SoDYNTkmG8Af5PC+qEFDqA1UnqDs3epJtK/SLLdRHNTJjesLXtgWL
8YxcVh0FQkDUBUmOomEfokGU1oda+jjxYcee/zF7IUcETenWRmM5RXPvMxOVeSsq
6ecc1z84gYiuD2qUR/WpZsA3A83K1O+kGhM56qkjlb9X1yco9vavw0NI+m70pSri
VhcETrIZZpT1I4G3DRPAnStnoLFyp44WGPd8S4G3dSjClA4+cdTphKZL5nKin02F
NGNB3sv+ubmsmsHUnTzkyr18iXKRbxMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
CQW2NW9GjtkcZRImC+l9hSlDZ5NYvgjGE67arPdrbS1EDjmpOdz7E7yLEU6mpzsO
xMsi5kta9rQhsOdbydz6swkkUxrhSm7lBbttkggHULN1dfhLMUmbBDCZ9cmfRZCo
D0dW+bHjH4aDd3X1uguoGjoxTMaR3EM5z663rA3ogjRTbsdag4sjlpoVah40y0vi
tVl4j/Uxn/VzzG1yGmPffrv8AWG4Zll9ZjIowbE9MnHdcMgj6sPBYJ7J1iVwlRMj
9F8SeUPTzQhnh/40TH3KNVU6QSb5J1W4gCrRwxQ0HDlCZOAZyL5JJoIlGTqCbF5b
AcPvBc/ggs5jNB6jaqLJ/A==
-----END CERTIFICATE-----";}
```

Related `saml_x509_certificate.ini` file looks good with header `<<<serialized>>> <<<serialized>>> <array>` identifying double serialization (supported in VersionPress, see #1234).
[saml_x509_certificate.zip]
Only problem is maybe (?) `rn` as end of lines (see attached file).
https://github.com/versionpress/versionpress/files/3130401/saml_x509_certificate.zip

After running `wp vp apply-changes`, database entry is damaged to `s:24:"<<<serialized>>> <array>";`

It looks like a bug related to double serialization, maybe connected with multiline string, I am not sure yet.

**Update:** It is not related to multiline strings (even if we should also check line replacing), but double serialization. You can use following example:
`update_option( 'double_serialization', maybe_serialize( array( 'Value' ) ) );`

In database is correctly saved `double_serialization` value as `s:22:"a:1:{i:0;s:5:"Value";}";`

File `double_serialization.ini` looks good:
```
[double_serialization]
option_value = <<<serialized>>> <<<serialized>>> <array>
option_value[0] = "Value"
autoload = "yes"
```
But after running `wp vp apply-changes`, database entry is also damaged to `s:24:"<<<serialized>>> <array>";`

I am not sure if created `.ini` file (especially syntax `<<<serialized>>> <<<serialized>>> <array>`) is wrong or problem is related to applying changes to database.

**Comment by pavelevap** [comment]
There are several possible situations and our tests cover only some of them:

**Serialized string in a serialized string** :no_entry_sign: 
Test: PR #1435 (?)
Test code: `serialize(serialize('some string'));`
WP test code: `update_option( 'double_serialization', serialize( 'Value' ) );`
PHP result: `s:12:"s:5:"Value";";`
`.ini` result: `option_value = <<<serialized>>> <<<serialized>>> "Value"`
Sync back to database: `s:24:"<<<serialized>>> "Value"";` :exclamation: 

**Serialized string in a serialized array** :heavy_check_mark: 
Test: [serializedStringInSerializedArray](https://github.com/versionpress/versionpress/blob/380f41d55d106d9f45bd0c4931cbac7eb0e3dac3/plugins/versionpress/tests/Unit/IniSerializerTest.php#L1549)
Test code: `serialize([serialize('some string')]);`
WP Test code: `update_option( 'double_serialization', [ serialize( 'Value' ) ] );`
PHP result: `a:1:{i:0;s:12:"s:5:"Value";";}`
`.ini` result:
```
option_value = <<<serialized>>> <array>
option_value[0] = <<<serialized>>> "Value"
```
Sync back to database: `a:1:{i:0;s:12:"s:5:"Value";";}`

**Serialized array in a serialized array** :heavy_check_mark: 
Test: [serializedArrayInSerializedArray](https://github.com/versionpress/versionpress/blob/380f41d55d106d9f45bd0c4931cbac7eb0e3dac3/plugins/versionpress/tests/Unit/IniSerializerTest.php#L1528)
Test code: `serialize([serialize(['some string'])]);`
WP test code: `update_option( 'double_serialization', [ serialize( ['Value'] ) ] );`
PHP result: `a:1:{i:0;s:22:"a:1:{i:0;s:5:"Value";}";}`
`.ini` result:
```
option_value = <<<serialized>>> <array>
option_value[0] = <<<serialized>>> <array>
option_value[0][0] = "Value"
```
Sync back to database: `a:1:{i:0;s:22:"a:1:{i:0;s:5:"Value";}";}`

**Serialized array in a serialized string** :no_entry_sign: 
Test -
Test code: `serialize(serialize(['some string']));`
WP test code: `update_option( 'double_serialization', serialize( ['Value'] ) );`
PHP result: `s:22:"a:1:{i:0;s:5:"Value";}";`
`.ini` result:
```
option_value = <<<serialized>>> <<<serialized>>> <array>
option_value[0] = "Value"
```
Sync back to database: `s:24:"<<<serialized>>> <array>";` :exclamation:

**Comment by borekb** [comment]
Awesome summary, @pavelevap!

**Comment by candrews** [comment]
@borekb @pavelevap my PR at https://github.com/versionpress/versionpress/pull/1435 includes tests for the 2 failing test cases and also includes a fix for those failures. I think it's ready to merge, solving VP's issues with multiple serialization.

**Comment by pavelevap** [comment]
Thank you, @candrews, I will check your fix, tests seems OK.

I will probably create different issue, but it seems to me that there is still another problem with multiline strings (but it is not related to double serialization).

I tested following code:
```
update_option( 'lines', 'First row
Second row
Third row' );
```
Following value is correctly saved in database:
```
First row
Second row
Third row
```
But `.ini` file contains
```
[lines]
option_value = "First rownSecond rownThird row"
autoload = "yes"
```
And after running `wp vp apply-changes` it is damaged also in database.

Can you confirm, that it is also issue for you and not only my Windows problem?

**Comment by candrews** [comment]
> I will probably create different issue, but it seems to me that there is still another problem with multiline strings (but it is not related to double serialization).

I tracked that down - it's definitely an issue. The problem is in the query parsing, not in the serializer. I created https://github.com/versionpress/versionpress/issues/1436  to track it.
