### ISSUE TITLE
Slashes are stripped from values in INSERT queries, breaking some data

### ISSUE THREAD

**Issue by candrews** [versionpress/versionpress#1436]
To reproduce this issue, create a new file called `test.php`:
```
<?php
require( dirname( __FILE__ ) . '/wp-load.php' );
update_option( 'lines6', 'First row
Second row
Third row' );
```

Then run it by hitting the URL in the browser.

Actual:
```
$ cat wp-content/vpdb/options/li/lines6.ini 
[lines6]
option_value = "First rownSecond rowXnThird row"
autoload = "yes"
```
Expected:
```
$ cat wp-content/vpdb/options/li/lines6.ini 
[lines6]
option_value = "First row
Second row
Third row"
autoload = "yes"
```

Interesting, executing `test.php` a second time results in the expected data being written to the ini file. So the issue is only happening for INSERTs (not for UPDATEs).

**Comment by candrews** [comment]
The problem is caused by `stripslashes` being run on the value in the query.

In `SqlQueryParser.getColumnDataToSet`, the value being passed in as `$sqlStatement` is:
```
INSERT  INTO `wp_options`(`option_name`, `option_value`, `autoload`) VALUES ('lines6', 'First row\nSecond row\nThird row', 'yes') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`)
```

The value returned by that function is:
```
Array
(
    [0] => Array
        (
            [option_name] => lines6
            [option_value] => First rownSecond rownThird row
            [autoload] => yes
        )

)
```

The `\` is stripped from the value.

**Comment by candrews** [comment]
slash stripping was introduced in this commit: https://github.com/versionpress/versionpress/commit/6ecaf8d0b481497e46ec3bd4c89773f17cab4177#diff-8543550ac24ac9966fa13dde4cc7cad3

I believe what actually should be done is basically the inversse of [mysqli_real_escape_string](https://www.php.net/manual/en/mysqli.real-escape-string.php); `\n`, `\r`, `\t`, `\0` should be replaced by their actual characters.


@pavelevap @borekb thoughts?

**Comment by candrews** [comment]
Ah, the solution is simple: `stripcslashes` should be used, not `stripslashes`

The problem was caused by a simple one character mistake made over 3 years ago :)

**Comment by pavelevap** [comment]
:heart: Good catch, @candrews! I rememeber that I was not able to reproduce this issue yesterday evening :-) I suspected line endings, but it was strange.

Also my example with `rn` from #1430 would be fixed, I guess: https://github.com/versionpress/versionpress/files/3130401/saml_x509_certificate.zip

We should probably cover it with some test.

**Comment by candrews** [comment]
> No other wrong `stripslashes()` usage throughout VP code?

Looking through the output of `git grep stripslashes`, I don't see any other wrong usages.

**Comment by candrews** [comment]
> We should probably cover it with some test.

I updated the PR with some tests.
