### ISSUE TITLE
Possible implementation: choose the git to commit and suspend feature

### ISSUE THREAD

**Issue by UncleDan** [versionpress/versionpress#1472]
Is it possibile to have the ability to choose whiche repo to commit to (via WP dashboard).

Is it possible to have a "suspend" feature or not to loose the anchor when deactivating the plugin? It brakes duplicator and other plugins I use but if I disable it I loose the previous undo (it is clearly stated, I know, but a bit annoying!)

**Comment by borekb** [comment]
Hi @UncleDan, it's not possible to choose which Git repo to commit to, and we don't plan to implement such feature. VersionPress commits to a Git repo found at site root and it has to be this way.

As for the "suspend" feature, VersionPress needs to be actively tracking changes, and _all_ changes, to be able to undo them. So when you deactivate VersionPress, you lose the ability to revert older changes, and there's not much we can do about it.

Hope this explains it a bit, I'll close the issue as we don't plan to act on it but feel free to comment further. Thanks.
