### ISSUE TITLE
Support Git 1.7+

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#239]
_This is an imported issue, original reference WP-239, created on 02 Jan 2015._

Git 1.8 is still quite common, for example, Azure Websites currently (January 2015) use Git 1.8.4 and some Linux distributions are even bundled with Git 1.7. VersionPress 1.0 should support Git 1.7+ if all tests pass with it.

Problems related to the required Git version that we already encountered:
- `git add -u` in 1.8 does not support code syntax `path/*` which caused problem during plugin / theme deletion (email by Martin Hujer).
  - Probably solved in commit https://github.com/versionpress/versionpress/commit/62bca0f1862fb72673a19c5d73b0e40cfc9fc2c1 when we switched from `-u` to `-A` (needs testing).

---

Other possibly useful information

Release dates for main Git versions:
-   1.7: September 2010
-   1.8: October 2012
-   1.9: February 2014
-   2.0: May 2014 (No release for Windows in January 2015)
-   2.1: August 2014 (No release for Windows in January 2015, currently only 1.9.5)
-   2.2: November 2014 (No release for Windows in January 2015, currently only 1.9.5)

(Release dates can be found e.g. here: https://github.com/git/git/tree/master/Documentation/RelNotes, for Windows: https://github.com/msysgit/msysgit/releases/)

**Comment by ramnathk** [comment]
Supporting 1.8 will really open up the plugin to several shared hosts as well. Could you please reconsider? I am on BigRock.in which has 1.8.2.3

**Comment by borekb** [comment]
@ramnathk If someone wants to make it work Git < 1.9, we'll gladly accept a PR for it. For the near future, though, there are more important things from our point of view to work on.
