### ISSUE TITLE
Store post format into 'VP-Post-Format' and improve the change message

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#355]
_This is an imported issue, original reference WP-355, created on 13 Apr 2015._

Currently, the post format is an usual postmeta for VersionPress. Maybe it would be better to show message like:

> Created quote 'xyz'

instead of

> Created post 'xyz'

To do this, a tag `VP-Post-Format` would be handy, but maybe getting the type from postmeta will be difficult.

**Comment by pavelevap** [comment]
It seems to me a little bit messy :-(

> Created gallery 'xyz'

It is not immediatelly clear if `gallery` is `post_format` or `post_type`. I would expect that the first information will be the same (`post_type`) for all post items. Adding info about post format is a great idea, but post formats can be active also for different post types (not only post). For example something like this:

> Created post:gallery 'xyz'
