### ISSUE TITLE
Better error message for PHP lower than 5.6

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#370]
*This is an imported issue, original reference WP-370, created on 27 Apr 2015.*

It can be done like [this](http://wordpress.stackexchange.com/q/76007/12248). There should be only PHP 5.2 compatible code in `versionpress.php`.

**Comment by JanVoracek** [comment]
All hooks using the `__FILE__` constant are broken after moving code from `versionpress.php` to `setup-hooks.php`. Reopening.
