### ISSUE TITLE
Tests for new GUI

### ISSUE THREAD

**Issue by vasek17** [versionpress/versionpress#421]
_This is an imported issue, original reference WP-421, created on 05 Aug 2015._

Testing JS-heavy apps using Selenium is inconvenient - for example, it's not easy to catch going to a new URL, sending forms etc. See e.g. [this article](http://joelotter.com/2015/04/18/protractor-reactjs.html). For this reason, there will be two kinds of tests for the new GUI:
1. Tests of the UI alone (using React Test Utilities) - main emphasis on testing HTTP requests and handling responses.
2. Tests of the API endpoints.

**Comment by borekb** [comment]
Let's open a fresh issue when (and if) we need it.
