### ISSUE TITLE
Check codestyle 

### ISSUE THREAD

**Issue by JanVoracek** [versionpress/versionpress#629]
Sometimes the code isn't in accordance with the [PSR-2](http://www.php-fig.org/psr/psr-2/) standard – mostly we're violating the "brace on the next line" rule on classes and their methods. We should fix it.

Also would be great to have the style checker on our CI.

**Comment by JanVoracek** [comment]
Code Sniffer should be only a dev dependency. Reopening.

**Comment by borekb** [comment]
Still some small things to fix like IDEA newline settings, some manual steps seem to be required (specifying path to `phpcs`) etc. Reopening.
