### ISSUE TITLE
Best practices integrating with third-party plugins 

### ISSUE THREAD

**Issue by danielbachhuber** [versionpress/versionpress#684]
To better understand the end state of integrating VersionPress with third-party plugins, I installed [Co-Authors Plus](https://wordpress.org/plugins/co-authors-plus/) locally.

Co-Authors Plus is a plugin to permit assigning multiple bylines to a post, something that WordPress doesn't support natively. Co-Authors Plus uses an `author` custom taxonomy to manage relationships between WordPress users and their posts. Furthermore, it also supports creating "guest authors" to assign as bylines to posts. Guest author data is stored as a custom post type, but then uses a corresponding `author` term to create the relationship between a guest author post and a bylined post (guest author CPT <-> author custom taxonomy term <-> normal post).

In the screenshots that follow, I:
- Created a new post.
- Assigned an existing WordPress user "daniel" as a byline on the post.
- Created a new guest author "Daniel Guest Author"
- Assigned "Daniel Guest Author" as a byline on the post.
- Generate a "testsubscriber" author term because such is the behavior of Co-Authors Plus — it creates new terms from users on the fly when you use the ajax search, because the actual search is performed against the description field on the terms.

![image](https://cloud.githubusercontent.com/assets/36432/12751981/097959d0-c975-11e5-9750-b543a25eb0b3.png)

Here's the VersionPress commit log it generated:

![image](https://cloud.githubusercontent.com/assets/36432/12751767/dfa0c054-c973-11e5-8c74-e50c0be955b5.png)

![image](https://cloud.githubusercontent.com/assets/36432/12751789/006b8a62-c974-11e5-999c-b03bfe2cc2db.png)

![image](https://cloud.githubusercontent.com/assets/36432/12751798/12a5cd82-c974-11e5-9c5a-91015c4f7181.png)

![image](https://cloud.githubusercontent.com/assets/36432/12751805/1baf077c-c974-11e5-9c31-593cdfe8953a.png)

![image](https://cloud.githubusercontent.com/assets/36432/12751823/2c6f669c-c974-11e5-8b05-3735c461d5ba.png)

Commentary on this storage structure aside, as VersionPress becomes more popular, you'll get exposed to all of the weird things WordPress plugins do. And you'll want to integrate VersionPress with these plugins, to provide a better, more expected experience for the end user.

Here are a couple of product problems I see:
- Incorrect language is used in the VersionPress commit log, as it relates to Co-Authors Plus data changes. This is because Co-Authors Plus has a higher-level understanding of how it's using WordPress' primitive data types, but VersionPress doesn't have access to this higher-level understanding.
- Similarly, VersionPress has a different understanding of data transactions than Co-Authors Plus does. In the example above, the "Daniel Guest Author" custom post type is tied to its author term. It shouldn't be possible to revert one without also reverting the other. Also, reverting the custom post type should (ideally) revert all of its assigned bylines in a single transaction. Otherwise, VersionPress can awkwardly destroy Co-Authors Plus' data structure.

To help us frame the conversation about potential solutions, what other product problems are you aware of, and what's your ideal end state for VersionPress integration with other plugins?

**Comment by danielbachhuber** [comment]
@borekb In hindsight, how do you feel about this task you embarked upon?

**Comment by borekb** [comment]
Hi Daniel, VersionPress 4.0 is all about this. It introduces [plugin definitions](https://github.com/versionpress/versionpress/blob/f6be4170265a7d366c0050891f1c857f971cc596/docs/Plugin-Support.md) that are the glue between plugins and VersionPress. There is probably no simpler way as Mergebot, the other database merging project, is building [something similar](https://github.com/deliciousbrains/mergebot-schemas).

Who thought this would be easy? 😃
