### ISSUE TITLE
Check compatibility with WordPress 4.5

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#750]
With WordPress 4.5 beta 1 [just released](https://wordpress.org/news/2016/02/wordpress-4-5-beta-1/), we should check that VersionPress is compatible with it. If it's not, there will be no 2.3 compatibility release (like we had with WP 4.4 and VP 2.2), we'll wait for VP 3.0 with possible fixes.

**Comment by borekb** [comment]
WordPress 4.5 is going to be released today and [VersionPress 3.0-beta](https://github.com/versionpress/versionpress/releases/tag/3.0-beta) is not yet entirely compatible – some tests are failing.

The final 3.0 release will support WP 4.5.

**Comment by unclhos** [comment]
What are the compatibility issues that are currently known? Anything big that I should keep from upgrading to 4.5 for now?

**Comment by JanVoracek** [comment]
We don't expect any issues. Some features (like theme logo) are already covered are we will most likely only update our tests. However, we need to check it more closely to be sure.

**Comment by octopuss** [comment]
Unfortunatelly some Selenium tests are failing in 4.5. I'll fix them.
