### ISSUE TITLE
Open-source VersionPress

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#787]
Placeholder ticket for now. Let's summarize here what changed when moving to the OSS development model.

**Comment by gianpaj** [comment]
i guess you can close this? :dancer: :laughing:

**Comment by borekb** [comment]
You're right :) Here is a summary:

We made the repo public yesterday – **Apr 6, 2016** – and published [**a blog post**](https://blog.versionpress.net/2016/04/going-open-source/) about it. Also, [**3.0-beta**](https://github.com/versionpress/versionpress/releases/tag/3.0-beta) was made available.

Merged into master are now:

- [README.md](https://github.com/versionpress/versionpress/blob/master/README.md) with proper project description
- [CONTRIBUTING.md](https://github.com/versionpress/versionpress/blob/master/CONTRIBUTING.md) with details on our development process, contribution flow etc.
- Issue and PR templates

All of that as part of PR https://github.com/versionpress/versionpress/pull/767.

Cheers from (a part of) the core team!

![2016-04-07 11_37_27-clipboard](https://cloud.githubusercontent.com/assets/101152/14347066/5919216e-fcb5-11e5-8c74-a3065b182580.png)

**Comment by gianpaj** [comment]
:beers: cheers!

**Comment by borekb** [comment]
As part of the open-sourcing effort, we also moved from BitBucket & JIRA to GitHub. This is a note about the migrated issues, originally stored [here](https://github.com/versionpress/versionpress/blob/9e0607024b77e64dc5b5839b3a73f49316a74fb7/docs/content/en/developer/development-process.md#note-on-imported-issues-1522):

---

### Note on imported issues 1..522

In the early days, we used JIRA and the Czech language to track the project (*bad* decision in retrospect 😅), with the earliest issues not even up to the common standards as we were a team of two and discussed many things face to face.

In October 2015, we decided to move to GitHub and take the project **history** with us, both on the repo level (no "initial commit" with thousands of lines of code) and the issues. The issues were not fun as we needed to write a migration script, fight the GitHub API limitations (e.g., dates cannot be set properly) and eventually translate the issues to English. But there's valuable information in there so we didn't want to throw that part of the project history away.

Still, please consider **issues #1 through #522 "quick and dirty"** – the translation may be poor, the issues may not explain everything in detail, etc.

For newer issues, we try to make them useful and high-quality; they are one of our key artifacts.
