### ISSUE TITLE
IDs in widgets

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#814]
Some widgets can contain entity references in them, e.g., this *Pages* widget:

![2016-03-23 14_18_39-widgets updated wordpress](https://cloud.githubusercontent.com/assets/101152/13986396/810d9416-f102-11e5-9360-17da2b98f1ba.png)

We need to describe them in `schema.yml` and handle them correctly.

- _This issue is blocked by #829_

**Comment by JanVoracek** [comment]
It's fixed by #829.
