### ISSUE TITLE
Old commits not ignored when searching

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#874]
Users can for example "Undo" commits from previous VP version, see attached screens.

Before search
![before_search](https://cloud.githubusercontent.com/assets/3008007/14329646/cba19618-fc3c-11e5-9bd8-dbe5c8666b40.jpg)

After searching "post"
![after_search](https://cloud.githubusercontent.com/assets/3008007/14329650/d3d7c99c-fc3c-11e5-887f-1b06463c7c00.jpg)

**Comment by vasek17** [comment]
@pavelevap: Nice one! It was not easy to reproduce it.
