### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by bankerrahul** [versionpress/versionpress#879]
Plugin could not be activated because it triggered a fatal error.

Warning: require_once(/public_html/wppartners.io/wp-content/plugins/versionpress/vendor/autoload.php): failed to open stream: No such file or directory in /public_html/wppartners.io/wp-content/plugins/versionpress/bootstrap.php on line 57

**Comment by borekb** [comment]
Hi, this is a support issue, could you please open a new ticket [here](https://github.com/versionpress/support)? Thank you.

**Comment by ruben-** [comment]
@bankerrahul: https://github.com/versionpress/versionpress scroll down to point 2 of getting started.
