### ISSUE TITLE
Display warning when someone clones the repo and uses the plugin as-is

### ISSUE THREAD

**Issue by JanVoracek** [versionpress/versionpress#880]
If someone just clones this repository a copies `plugins/versionpress` into his `wp-content` it fails on a warning. See versionpress/support#30 for an example.

VersionPress should print some nice error message 🙊  (maybe with a link to the GH releases).

**Comment by borekb** [comment]
Sounds good. From the error message, we could directly link to the correct ZIP file (GitHub API provides this I believe).

**Comment by octopuss** [comment]
Guys, i did not found any nice error message except this one in the screenshot. Plugin code is executed after user clicks "Activate" button, so I was unable to let him know that something is wrong before his action. If I hook something on plugin activation, WordPress always shows success  "Plugin activated" message + possibly custom notice. All solutions how to let user know that something is not right and disable activation process led to combination of `register_activation_hook` and `wp_die`. That results in page below

<img width="768" alt="screen shot 2016-04-13 at 9 18 22 am" src="https://cloud.githubusercontent.com/assets/2697437/14485666/b6191d54-0158-11e6-9cdc-8530f3021b69.png">

User is directed to Development setup page, or to GitHub latest release [page](https://github.com/versionpress/versionpress/releases/latest) which redirects him to 2.2 release. There is no easy way to link to zip download. Although the [api](https://api.github.com/repos/versionpress/versionpress/releases/latest) contain link to zip file, i think that it is not worth to parse it somehow, and return the correct url to user. What do you think ?

**Comment by borekb** [comment]
I like this approach, it will just need some polishing. This should be discussed in a PR, please open one.
