### ISSUE TITLE
Selenium test fails on UsersTest::editingMultipleUsermetaCreatesBulkAction.

### ISSUE THREAD

**Issue by octopuss** [versionpress/versionpress#889]
Test fails only when Selenium is used.

```
Commit is not a bulk action
~/Work/projects/versionpress/plugins/versionpress/tests/Utils/CommitAsserter.php:157
~/Work/projects/versionpress/plugins/versionpress/tests/End2End/Users/UsersTest.php:153
```

**Comment by octopuss** [comment]
The problem is caused by enhancing data going for update with data from database. https://github.com/versionpress/versionpress/blob/5b449973459d994d471c505b6e086329adec533f/plugins/versionpress/src/Database/WpdbMirrorBridge.php#L213. Select of current database state should be performed also when inserting data.

**Comment by borekb** [comment]
Created #900 which describes the issue on a slightly higher level. This issue will be resolved by it so I'm closing it.
