### ISSUE TITLE
Missing environment when committing through VP admin

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#895]
When I commit some uncommitted changes directly through VP administration, environment information is missing.

![missing_environment](https://cloud.githubusercontent.com/assets/3008007/14384005/eabb1f26-fd98-11e5-9940-23c6f91a51d4.jpg)

**Comment by octopuss** [comment]
@vasek17, @pavelevap : Is it frontend or backend error. What does the commit message contain ?

**Comment by vasek17** [comment]
The commit message is simply the text that user enters in the commit dialog.
We should add at least the `X-VP-Environment` at the bottom of the commit message.

I'm not sure if it will be displayed correctly without the `VP-Action` in the commit message.

**Comment by borekb** [comment]
Related: https://github.com/versionpress/versionpress/issues/849

**Comment by JanVoracek** [comment]
`UntrackedChangedInfo` is now encapsulated in `ChangeInfoEnvelope` to track the environment of manual commits. However, `CommitAsserter` cannot handle it and causes failures in `GitRepositoryTests\RevertTest`.

Reopening to fix the `CommitAsserter`.
