### ISSUE TITLE
INSERT does not store all the columns

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#900]
Most commonly, WordPress provides full data to the `insert()` method, i.e., it sends a PHP array with all the columns that will become rows in the INI files. However, it's not always guaranteed, for instance, `user_status` field when inserting a new user is missing. This leads to an INI file that is not a 100% mirror of the database row.

It's technically not a big problem because when doing files -> DB synchronization, the missing value will simply create a cell with the default value in the database and all will work fine. However, when the entity is updated, VersionPress merges the data provided by the `update()` method with a SELECT of the row, which creates a new line in the INI file unrelated to the actual change and it causes subtle issues like #889.

The most bullet-proof behavior would be to always store every column in the INI file on `insert()`, i.e., combine the data provided by the `insert()` method with a SELECT into the database.

Another thing to consider is **DBAsserter**. Maybe it should do a strict comparison and fail when there are DB columns that do not have equivalent INI lines, and vice versa. This DBAsserter would ensure that the INI files are a complete mirror of the DB.

**Comment by octopuss** [comment]
I think that reason why DbAsserter failed on this one is here : https://github.com/versionpress/versionpress/blob/db645ea95a9f4b4016878b453ccedb0779ca3e0d/plugins/versionpress/tests/Utils/DBAsserter.php#L123-L123. If the column is not found in database, it is skipped and db state is considered equal to a file.

**Comment by borekb** [comment]
@octopuss: I wouldn't say the DBAsserter "failed", it was just implemented differently in the past. But we should probably change its behavior if there's no reason against it. Do you plan to do that as part of PR #904?

**Comment by octopuss** [comment]
@borekb : no it will not be part of #904, i think that it deserves separate issue, because change I think that change in DbAsserter can cause several other tests to fail. I will create issue for that.

**Comment by borekb** [comment]
Changing the DBAsserter was an integral part of this issue as it should have tested the functionality you've implemented in PR #904. But OK, no big deal, let's do it in a separate issue then.
