### ISSUE TITLE
Committer creates leftover [user] and [push] in .git/config

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#921]
This is part of my .git/config after running VersionPress for a while:

```
[merge "vp-ini"]
        name = VersionPress ini merge driver
        driver = "C:/wamp/bin/php/php7.0.0/php.exe" "C:/wamp/www/staging/wp-content/plugins/versionpress/src/Git/merge-drivers/ini-merge.php" %O %A %B
        recursive = text
[user]
[user]
[user]
[user]
[user]
[user]
[user]
[push]
```

My best guess is that those are left-overs from temporarily setting a commit user in the Committer, but I could be wrong.

**Comment by pavelevap** [comment]
Same problem, I did not notice it earlier, but I can confirm many `[user]` rows.

**Comment by vasek17** [comment]
Git doesn't remove empty sections of config file after calling `git config --unset some.key` and doesn't reuse them when calling `git config some.key value`.

It is possible to manually remove the whole section with `git config --remove-section user` when both local user name and email are empty [here](https://github.com/versionpress/versionpress/blob/52d257e9871c7be3e6b586d5d30fee11b7d9eca7/plugins/versionpress/src/Git/GitRepository.php#L82). However when the `user` section of git config contains more values than `name` and `email` it will be removed.

Possibly related: http://stackoverflow.com/questions/15935624/how-do-i-avoid-empty-sections-when-removing-a-setting-from-git-config

**Comment by borekb** [comment]
But how do the empty sections appear there in the first place? Was I right with the Committer guess or is that something else?

**Comment by vasek17** [comment]
Yes, it is the [Committer](https://github.com/versionpress/versionpress/blob/52d257e9871c7be3e6b586d5d30fee11b7d9eca7/plugins/versionpress/src/Git/GitRepository.php#L82)
