### ISSUE TITLE
VpidRepository::deleteId failed

### ISSUE THREAD

**Issue by ENM1989** [versionpress/versionpress#929]
In the case of a change the deleteId method of the VpidRepository class is called.
But the executed query failed:

DELETE FROM  WHERE `table` = "postmeta" AND id = '{id}'

The environment:
VP: The current master branch
WP: 4.4.2
OS: Debian 8.4

**Comment by octopuss** [comment]
Hello and thank you for your report. It is definetly a bug so I will fix it. I think that you can fix it in your code by changing following line, but i will look at it closer.

https://github.com/versionpress/versionpress/blob/71b83c9eb9a49a5e3383cf66c43847d9b54b6a36/plugins/versionpress/src/Database/VpidRepository.php#L157-L157

to 

```php
$deleteQuery = "DELETE FROM {$this->vpidTableName} WHERE `table` = \"$tableName\" AND id = '$id'";
```

Ivan.

**Comment by borekb** [comment]
@ENM1989 This has actually been the very first (good) external bug report, thank you! Props awarded :)

**Comment by ENM1989** [comment]
@octopuss @borekb Thanks for the quick correction and your answers.
