### ISSUE TITLE
Errors on changing Permalink settings to Post name

### ISSUE THREAD

**Issue by re2me** [versionpress/versionpress#940]
Hello,

On changing my Permalink structure from Plain to anything else (I specifically need Post name), VersionPress does not load its GUI.  

Chrome F10 shows:
http://minos/wp-json/versionpress/display-welcome-panel Failed to load resource: the server responded with a status of 404 (Not Found)
http://minos/wp-json/versionpress/commits?page=0&query= Failed to load resource: the server responded with a status of 404 (Not Found)

Wordpress 4.4.2 (also occurred with 4.5)
VersionPress 3.0Beta (also occurred with 2.2)

**Comment by pavelevap** [comment]
Similar (not resolved) support issues: https://github.com/versionpress/support/issues/13, https://github.com/versionpress/support/issues/29

Could you please share your [System info](http://docs.versionpress.net/en/troubleshooting/system-info-page)?

**Comment by re2me** [comment]
Attached:
[System info.txt](https://github.com/versionpress/versionpress/files/223839/System.info.txt)

**Comment by borekb** [comment]
@re2me Can you try to reproduce it on vanilla WordPress please? Our best guess is that some plugin is causing this.

**Comment by JanVoracek** [comment]
It's probably caused by some interference with other plugins. Hopefully, we will be able to reproduce it and solve it in 4.0. Closing for now.

**Comment by karpstrucking** [comment]
For anyone else that found this via a search, the solution in my case (vanilla WP 4.5.3 and VP 3.0.1) was related to Apache config: the `AllowOverride` directive had to be updated for the vhost to `All`
