### ISSUE TITLE
PHP Warnings by commit

### ISSUE THREAD

**Issue by ENM1989** [versionpress/versionpress#941]
The VersionPress GUI tells me, that i have uncommited changes.
If i want to commit these changes, a POST is send to https://{my_url}/wp-json/versionpress/commit.
The response contains some PHP Warnings:

- Warning: Illegal string offset 'vp_id' in /{my_wordpress_path}/wp-content/plugins/versionpress/src/Synchronizers/SynchronizerBase.php on line 152
- Warning: Illegal string offset 'parent' in /{my_wordpress_path}/wp-content/plugins/versionpress/src/Synchronizers/SynchronizerBase.php on line 152
- Warning: Illegal string offset 'vp_id' in /{my_wordpress_path}/wp-content/plugins/versionpress/src/Synchronizers/SynchronizerBase.php on line 154
- Warning: Illegal string offset 'vp_id' in /{my_wordpress_path}/wp-content/plugins/versionpress/src/Synchronizers/SynchronizerBase.php on line 305
- Warning: Illegal string offset 'vp_id' in /{my_wordpress_path}/wp-content/plugins/versionpress/src/Synchronizers/OptionsSynchronizer.php on line 111

Because of this, the response is not valid and the following error message is shown:
Connection Error: VersionPress is not able to connect to WordPress site. Please try refreshing the page.

The environment:
VP: The current master branch (the same branch that was used in https://github.com/versionpress/versionpress/issues/929)
WP: 4.4.2
OS: Debian 8.4

**Comment by JanVoracek** [comment]
Hi, thanks for flagging.

Just adding steps for reproduction:

1. Install and fully activate VersionPress.
2. Change directly some INI file with option (for example `options/bl/blogname.ini`).
3. Do a manual commit from WP administration.
