### ISSUE TITLE
Update project dependencies

### ISSUE THREAD

**Issue by JanVoracek** [versionpress/versionpress#974]
According to `composer outdated` (below) we use several outdated libraries. Some of them are crucial for VersionPress (e.g. `symfony/process`) or heavily used (e.g. `nette/utils`). Also, there are some dependencies we no longer use, like `comment-stripper`. We should review these, too. 

<img width="780" alt="screen shot 2016-04-24 at 19 53 25" src="https://cloud.githubusercontent.com/assets/703215/14769293/4d8b1f60-0a56-11e6-83e2-e7bd3b6eaddf.png">

**Comment by JanVoracek** [comment]
We should also update the platform PHP version in `composer.json`.

**Comment by JanVoracek** [comment]
`composer.json` defines Tracy as a standard dependency while it should be a dev dependency.

**Comment by borekb** [comment]
I'll need this for dockerized dev setup (https://github.com/versionpress/versionpress/pull/1227) so will do it soon.
